import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { SCENARIO_REGISTRY } from "@content/scenarioRegistry";

// Keeps the picker honest: registry difficulty labels must match the latest
// balance-report suggested-labels.json (regenerated by
// `npx tsx scripts/balance-report.ts`). When the gauntlet moves a label, either
// re-run with WRITE_REGISTRY=1 or update the JSON + registry together.

const LABELS_PATH = join(process.cwd(), "docs", "balance", "suggested-labels.json");

describe("scenario registry difficulty labels", () => {
  it("suggested-labels.json exists (produced by balance-report)", () => {
    expect(existsSync(LABELS_PATH), `missing ${LABELS_PATH} — run scripts/balance-report.ts`).toBe(true);
  });

  it("every registry scenario's difficulty matches the gauntlet suggested label", () => {
    const raw = JSON.parse(readFileSync(LABELS_PATH, "utf8")) as {
      labels: Record<string, { suggested: string; authored: string }>;
    };
    const missing: string[] = [];
    const mismatches: string[] = [];
    for (const meta of SCENARIO_REGISTRY) {
      const row = raw.labels[meta.scenarioId];
      if (!row) {
        missing.push(meta.scenarioId);
        continue;
      }
      if (meta.difficulty !== row.suggested) {
        mismatches.push(`${meta.scenarioId}: registry=${meta.difficulty} suggested=${row.suggested}`);
      }
    }
    expect(missing, `registry scenarios missing from suggested-labels.json: ${missing.join(", ")}`).toEqual([]);
    expect(mismatches, `label mismatches — re-run balance-report with WRITE_REGISTRY=1:\n${mismatches.join("\n")}`).toEqual([]);
  });
});
