// ─────────────────────────────────────────────────────────────────────────
// COUNTRY GAME — the country-agnostic multiparty campaign.
//
// ukGame.ts proved the shape: regions with calibrated bloc appeals, the shared
// softmax vote model + seats curve (multiparty.ts), leaders whose traits scale
// action effectiveness, and a light weekly event. This module is that same
// game with every UK-specific import replaced by a `CountryBundle` parameter,
// so Canada, Germany, France (and any future country) are pure content drops.
// The UK path itself is intentionally untouched.
// ─────────────────────────────────────────────────────────────────────────

import type { PartyId, PoliticalSystem } from "./system";
import type { CauseEntry, Government, SeatResult, StateBloc, StateContest } from "./types";
import { createRng, hashSeed, type Rng } from "./rng";
import { computeSeatsResult, blocPartyShares, tallyRegion, softmax } from "./multiparty";
import { planMultipartyAi, type MpDifficulty } from "./multipartyAi";
import {
  buildCauseRecap,
  decayMultipartyTurn,
  finalizeMpCampaignTurn,
  resolvePendingChoiceGate,
} from "./mpTurnHelpers";

// ── Content bundle: everything a country ships ────────────────────────────
export interface CountryBlocDef {
  id: string;
  name: string;
  share: number;             // national electorate fraction (normalized per region)
  turnoutPropensity: number; // 0..1
  tilt: Record<PartyId, number>; // per-party logit nudge vs the region baseline
}

export interface CountryRegionMeta {
  id: string;
  name: string;
  abbr: string;
  seats: number;      // the region's awardable-unit pool
  electorate: number; // thousands of votes cast (weights the national aggregate)
  profile?: Record<string, number>; // per-bloc share multipliers
  // Rough cartogram position for the generic tile map.
  tile: { row: number; col: number };
  // Optional per-region FPTP amplification override (1.0 ≈ proportional).
  seatElasticity?: number;
}

export interface CountryRegionResult {
  v: Record<PartyId, number>; // real vote share per party
  s: Record<PartyId, number>; // real seats per party (sums to the region pool)
}

export interface CountryElectionData {
  id: string;
  year: number;
  label: string;
  tagline: string;
  salience: Record<string, number>;
  regions: Record<string, CountryRegionResult>;
  // Chamber-size override for elections fought under a different apportionment
  // (Canada 2021: 338 seats; Bundestag 2021: 735 with overhang). Region pools
  // come from the election's own seat data; this sets the winning post.
  majority?: { total: number; threshold: number };
  goalText?: string; // per-election goal line ("170 of 338 seats")
  // Named historical events for THIS election (the real story beats of the
  // campaign). Entries with a `turn` fire deterministically that week, once;
  // the rest join the country's generic pool in the weekly random draw.
  // Election-deck events never repeat within a game.
  events?: CountryEventDef[];
}

export interface CountryLeader {
  partyId: PartyId;
  name: string;
  charisma: number;
  energy: number;
  competence: number;
  machine: number;
}

export type CountryEventRole = "any" | "player" | "leader" | "challenger";

export interface CountryEventDef {
  id: string;
  headline: string; // {party} substituted with the target's short name
  role: CountryEventRole;
  weight: number;
  appeal?: number;
  momentum?: number;
  // Fixed target: this exact party is hit, regardless of role (for real
  // history — "Poilievre loses his own seat" always lands on the CPC).
  party?: PartyId;
  // Scheduled story beat: fires deterministically at this turn index (0-based)
  // instead of entering the random draw. Only meaningful on election decks.
  turn?: number;
  // Player-facing prompt when this event becomes a decision.
  prompt?: string;
  choices?: CountryEventChoice[];
}

export interface CountryEventChoice {
  id: string;
  text: string;
  resultText: string;
  appeal?: number;
  momentum?: number;
  rivalAppeal?: number;
}

export interface CountryIssueDef {
  id: string;
  name: string;
  blurb: string;
}

// Real-geography SVG map (same shape contract as the UK's regionPaths).
// `d` may contain multiple subpaths for multi-polygon regions; `label` is the
// text anchor. Generated by scripts/build_country_paths.cjs — do not hand-edit.
export interface CountryMapShapes {
  viewBox: string;
  shapes: Record<string, { d: string; label: [number, number] }>;
}

export interface CountryBundle {
  id: string;    // "CA" | "DE" | "FR"
  label: string; // "Canada"
  flag: string;
  currency: string;        // "$" | "€"
  unitName: string;        // "seat" | "point"
  unitNamePlural: string;  // "seats" | "points"
  goalText: string;        // "172 of 343 seats"
  system: PoliticalSystem;
  playable: PartyId[];
  abstaining: PartyId[];
  defaultSeatElasticity: number;
  issues: CountryIssueDef[];
  blocs: CountryBlocDef[];
  regions: CountryRegionMeta[];
  elections: Record<string, CountryElectionData>;
  leaders: Record<string, Partial<Record<PartyId, CountryLeader>>>;
  events: CountryEventDef[];
  eventChance: number;
  // Real-geography map; absent ⇒ the tile cartogram is the map.
  map?: CountryMapShapes;
  // Coalition-compatibility predicate (Germany's firewall, etc.).
  compatible?: (lead: PartyId, partner: PartyId) => boolean;
  // Country-specific framing of the outcome (France: "wins the presidency").
  governmentText?: (g: Government, partyName: (p: PartyId) => string) => string | undefined;
}

// ── Region construction (the country-parameterized ukSetup) ───────────────
const EPS = 1e-9;

function normalizeShare(v: Record<string, number>): Record<PartyId, number> {
  const sum = Object.values(v).reduce((s, x) => s + Math.max(0, x), 0);
  const out: Record<PartyId, number> = {};
  for (const p of Object.keys(v)) out[p] = sum > 0 ? Math.max(0, v[p]) / sum : 0;
  return out;
}

// Solve per-bloc appeals so the region's turnout-weighted aggregate hits the
// real result — same IPF as the UK builder, over this country's blocs.
function solveRegionBlocs(
  blocs: { id: string; size: number; turnout: number; tilt: Record<PartyId, number> }[],
  target: Record<PartyId, number>,
): StateBloc[] {
  const parties = Object.keys(target);
  const lnTarget: Record<PartyId, number> = {};
  for (const p of parties) lnTarget[p] = Math.log(Math.max(EPS, target[p]));
  const corr: Record<PartyId, number> = Object.fromEntries(parties.map((p) => [p, 0]));

  const appealFor = (b: { tilt: Record<PartyId, number> }): Record<PartyId, number> => {
    const a: Record<PartyId, number> = {};
    for (const p of parties) a[p] = lnTarget[p] + (b.tilt[p] ?? 0) + corr[p];
    return a;
  };

  for (let iter = 0; iter < 16; iter++) {
    const agg: Record<PartyId, number> = Object.fromEntries(parties.map((p) => [p, 0]));
    let totW = 0;
    for (const b of blocs) {
      const sh = softmax(appealFor(b));
      const w = b.size * b.turnout;
      for (const p of parties) agg[p] += w * sh[p];
      totW += w;
    }
    for (const p of parties) {
      const a = totW > 0 ? agg[p] / totW : target[p];
      corr[p] += Math.log(Math.max(EPS, target[p]) / Math.max(EPS, a));
    }
  }

  return blocs.map((b) => {
    const appeal = appealFor(b);
    const support = softmax(appeal);
    return {
      blocId: b.id as StateBloc["blocId"],
      size: b.size,
      turnoutPropensity: b.turnout,
      baselineMargin: 0,
      support: support as StateBloc["support"],
      campaignMargin: 0,
      enthusiasm: 1,
      appeal,
      campaignAppeal: Object.fromEntries(parties.map((p) => [p, 0])),
    };
  });
}

function buildRegionContest(country: CountryBundle, meta: CountryRegionMeta, res: CountryRegionResult): StateContest {
  const target = normalizeShare(res.v);
  // The election's own seat table defines the region pool, so one bundle can
  // host elections fought under different apportionments.
  const pool = Object.values(res.s).reduce((s, x) => s + x, 0) || meta.seats;
  const raw = country.blocs.map((b) => ({ def: b, share: b.share * (meta.profile?.[b.id] ?? 1) }));
  const totalShare = raw.reduce((s, r) => s + r.share, 0);
  const blocsIn = raw.map((r) => ({
    id: r.def.id,
    size: (meta.electorate * r.share) / totalShare,
    turnout: r.def.turnoutPropensity,
    tilt: r.def.tilt,
  }));

  return {
    id: meta.id,
    name: meta.name,
    abbr: meta.abbr,
    electoralVotes: 0,
    region: "Swing",
    prior2020DemShare: 0.5,
    mediaMarketCost: 1,
    battleground: false,
    blocs: solveRegionBlocs(blocsIn, target),
    groundGame: { dem: 0, rep: 0 },
    momentum: 0,
    seats: pool,
    baselineSeats: { ...res.s },
    baselineShare: target,
    seatElasticity: meta.seatElasticity ?? country.defaultSeatElasticity,
  };
}

export function buildCountryRegions(country: CountryBundle, election: CountryElectionData): StateContest[] {
  return country.regions
    .filter((meta) => election.regions[meta.id])
    .map((meta) => buildRegionContest(country, meta, election.regions[meta.id]));
}

// ── Game state (mirrors UkGameState, keyed by countryId) ──────────────────
export interface CountryResources {
  funds: number;    // millions, in the country's currency
  actions: number;
  maxActions: number;
  momentum: number;
}

export type CountryActionType =
  | "broadcast" | "rally" | "surrogate" | "fundraise" | "ground_game" | "gotv"
  | "canvass" | "oppo_research" | "debate_prep" | "policy_prep" | "issue_pivot";

export type CountryAdMode = "positive" | "contrast" | "issue";

export interface CountryAction {
  type: CountryActionType;
  party: PartyId;
  regionId?: string;
  targetParty?: PartyId;
  mode?: CountryAdMode;
  issueId?: string;
  spend?: number;
  day?: number;
}

export interface CountryResult {
  seats: Record<PartyId, number>;
  voteShare: Record<PartyId, number>;
  seatResults: SeatResult[];
  largestParty: PartyId;
  hung: boolean;
  government: Government;
  postMortem: CauseEntry[];
}

export interface CountryRecapItem {
  label: string;
  detail: string;
  marginDelta?: number;
}

export interface CountryPendingEvent {
  eventId: string;
  targetParty: PartyId;
}

export interface CountryGameState {
  countryId: string;
  seed: number;
  rngState: number;
  turn: number;
  totalTurns: number;
  phase: "campaign" | "result";
  electionId: string;
  label: string;
  tagline: string;
  playerParty: PartyId;
  parties: PartyId[];
  leaders: Record<PartyId, CountryLeader>;
  salience: Record<string, number>;
  regions: StateContest[];
  resources: Record<PartyId, CountryResources>;
  causes: CauseEntry[];
  queuedActions: CountryAction[];
  abstaining: PartyId[];
  news: { turn: number; text: string }[];
  // Election-deck event ids that already fired (they never repeat in a game).
  firedEvents?: string[];
  // Winning post for THIS election (chamber sizes vary across cycles).
  majority?: { total: number; threshold: number };
  // Underdog handicap setting (defaults to "normal" = identity for old saves).
  difficulty?: Difficulty;
  lastRecap: CountryRecapItem[];
  pendingEvent?: CountryPendingEvent | null;
  result?: CountryResult;
}

export function majorityFor(g: CountryGameState, country: CountryBundle): { total: number; threshold: number } {
  return g.majority ?? country.elections[g.electionId]?.majority ?? country.system.majority;
}

function activeParties(country: CountryBundle, election: CountryElectionData): PartyId[] {
  const set = new Set<PartyId>();
  for (const r of Object.values(election.regions)) {
    for (const p of Object.keys(r.v)) set.add(p);
    for (const p of Object.keys(r.s)) set.add(p);
  }
  const order = [...country.playable, ...country.system.parties.map((p) => p.id)];
  return [...set].sort((a, b) => order.indexOf(a) - order.indexOf(b));
}

export function playablePartiesIn(country: CountryBundle, electionId: string): PartyId[] {
  const election = country.elections[electionId];
  if (!election) return [...country.playable];
  const active = new Set(activeParties(country, election));
  return country.playable.filter((p) => active.has(p));
}

function leaderFor(country: CountryBundle, electionId: string, partyId: PartyId): CountryLeader {
  const name = country.system.parties.find((p) => p.id === partyId)?.shortName ?? partyId.toUpperCase();
  return (
    country.leaders[electionId]?.[partyId] ?? {
      partyId, name: `${name} leader`, charisma: 55, energy: 60, competence: 60, machine: 55,
    }
  );
}

export type Difficulty = "easy" | "normal" | "hard";

// Underdog handicap. `normal` is the identity element — every lever is a no-op,
// so neutral play stays byte-identical to the calibration baseline and the
// history-reproduction tests are untouched. `easy` hands a skilled human the
// tools to overturn even a landslide (a favorable national climate + a bigger
// operation + a sloppier opponent); `hard` is a mild headwind for the
// pure-challenge setting. Levers:
//   environment  — one-time tilt of every bloc's baseline appeal toward the
//                  player (logit; ~0.04 ≈ 1 two-party point). The heavy hitter:
//                  it brings out-of-reach regions into play.
//   persuasion   — multiplies how far the player's own campaigning moves a bloc.
//   aiPersuasion — the same multiplier on every rival party's campaigning.
//   funds/actions— one-time bonuses to the player's starting war chest + slots.
export interface CountryHandicap {
  funds: number; actions: number; persuasion: number; aiPersuasion: number; environment: number;
}
export const COUNTRY_HANDICAP: Record<Difficulty, CountryHandicap> = {
  easy:   { funds: 6, actions: 2, persuasion: 1.5, aiPersuasion: 0.5, environment: 0.9 },
  normal: { funds: 0, actions: 0, persuasion: 1.0, aiPersuasion: 1.0, environment: 0 },
  // Hard is a campaign-only headwind: no baseline (environment) shift, so a
  // dominant winner stays dominant — only genuinely knife-edge elections tip.
  hard:   { funds: 0, actions: 0, persuasion: 0.85, aiPersuasion: 1.1, environment: 0 },
};

// One-time favorable-climate tilt: add `env` logits to the player's appeal in
// every bloc, then refresh live support. No-op when env = 0 (normal/hard base).
function applyCountryEnvironment(regions: StateContest[], player: PartyId, env: number) {
  if (!env) return;
  for (const region of regions) {
    for (const bloc of region.blocs) {
      if (!bloc.appeal) continue;
      bloc.appeal[player] = (bloc.appeal[player] ?? 0) + env;
      bloc.support = blocPartyShares(bloc) as typeof bloc.support;
    }
  }
}

export interface NewCountryGameOptions {
  seed?: number | string;
  election?: string;
  playerParty?: PartyId;
  totalTurns?: number;
  difficulty?: Difficulty;
}

export function createCountryGame(country: CountryBundle, opts: NewCountryGameOptions = {}): CountryGameState {
  // Default to the NEWEST election. (Never ids[0]: JS enumerates integer-like
  // keys such as "2021" in ascending order regardless of insertion order, so
  // ids[0] silently picks the oldest cycle in multi-election bundles.)
  const ids = Object.keys(country.elections)
    .sort((a, b) => country.elections[b].year - country.elections[a].year);
  const election = country.elections[opts.election ?? ids[0]] ?? country.elections[ids[0]];
  const seed = typeof opts.seed === "string" ? hashSeed(opts.seed) : (opts.seed ?? Date.now()) >>> 0;
  const parties = activeParties(country, election);
  const playerParty =
    opts.playerParty && parties.includes(opts.playerParty)
      ? opts.playerParty
      : parties.find((p) => country.playable.includes(p)) ?? parties[0];

  const difficulty: Difficulty = opts.difficulty ?? "normal";
  const hc = COUNTRY_HANDICAP[difficulty];

  const leaders: Record<PartyId, CountryLeader> = {};
  for (const p of parties) leaders[p] = leaderFor(country, election.id, p);

  const resources: Record<PartyId, CountryResources> = {};
  for (const p of parties) {
    const machine = leaders[p].machine;
    const bonusF = p === playerParty ? hc.funds : 0;
    const bonusA = p === playerParty ? hc.actions : 0;
    resources[p] = {
      funds: 4 + machine / 10 + bonusF,
      actions: 5 + Math.round(leaders[p].energy / 40) + bonusA,
      maxActions: 5 + Math.round(leaders[p].energy / 40) + bonusA,
      momentum: 0,
    };
  }

  const regions = buildCountryRegions(country, election);
  applyCountryEnvironment(regions, playerParty, hc.environment);

  return {
    countryId: country.id,
    seed,
    rngState: seed,
    turn: 0,
    totalTurns: opts.totalTurns ?? 6,
    phase: "campaign",
    electionId: election.id,
    label: election.label,
    tagline: election.tagline,
    playerParty,
    parties,
    leaders,
    salience: { ...election.salience },
    regions,
    resources,
    causes: [],
    queuedActions: [],
    abstaining: [...country.abstaining],
    news: [],
    firedEvents: [],
    majority: { ...(election.majority ?? country.system.majority) },
    difficulty,
    lastRecap: [],
    pendingEvent: null,
  };
}

// ── Actions (same verbs + balance as the UK game) ──────────────────────────
const clamp = (x: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, x));
const findRegion = (g: CountryGameState, id?: string) => g.regions.find((r) => r.id === id);

function saturate(bloc: StateContest["blocs"][number], party: PartyId, raw: number): number {
  const acc = Math.abs(bloc.campaignAppeal?.[party] ?? 0);
  const room = Math.max(0.15, 1 - acc / 0.8);
  return raw * room;
}

function addAppeal(g: CountryGameState, region: StateContest, party: PartyId, cause: string, delta: number) {
  // Difficulty scales campaigning: the player's own effort by `persuasion`,
  // every rival's by `aiPersuasion`. Both are 1.0 on normal (identity).
  const hc = COUNTRY_HANDICAP[g.difficulty ?? "normal"];
  const scaled = delta * (party === g.playerParty ? hc.persuasion : hc.aiPersuasion);
  for (const bloc of region.blocs) {
    if (!bloc.campaignAppeal) bloc.campaignAppeal = {};
    bloc.campaignAppeal[party] = (bloc.campaignAppeal[party] ?? 0) + saturate(bloc, party, scaled);
  }
  g.causes.push({ turn: g.turn, stateId: region.id, cause, marginDelta: scaled });
}

const standsIn = (g: CountryGameState, party: PartyId) =>
  g.regions.filter((r) => r.baselineShare?.[party] !== undefined);

function topRivalIn(region: StateContest, party: PartyId): PartyId | undefined {
  const { shareByParty } = tallyRegion(region);
  return Object.keys(shareByParty)
    .filter((p) => p !== party && (shareByParty[p] ?? 0) > 0)
    .sort((x, y) => (shareByParty[y] ?? 0) - (shareByParty[x] ?? 0))[0];
}

export function applyCountryAction(g: CountryGameState, a: CountryAction, rng: Rng) {
  const res = g.resources[a.party];
  if (!res || res.actions < 1) return;
  const leader = g.leaders[a.party];
  const skill = 0.85 + leader.charisma / 400;
  const compSkill = 0.85 + leader.competence / 400;
  const region = findRegion(g, a.regionId);
  const spend = (need: number) => { if (res.funds < need) return false; res.funds -= need; return true; };

  switch (a.type) {
    case "canvass": {
      if (!region) return;
      res.actions -= 1;
      addAppeal(g, region, a.party, `${leader.name} doorstep campaign in ${region.abbr}`, 0.05 * skill * (0.9 + rng.next() * 0.2));
      break;
    }
    case "ground_game": {
      if (!region) return;
      if (!spend(1.5)) return;
      res.actions -= 1;
      region.momentum = clamp(region.momentum + 2, -100, 100);
      addAppeal(g, region, a.party, `${leader.name} field operation in ${region.abbr}`, 0.075 * (0.85 + leader.machine / 300));
      break;
    }
    case "gotv": {
      if (!region) return;
      if (!spend(1)) return;
      res.actions -= 1;
      addAppeal(g, region, a.party, `${leader.name} GOTV drive in ${region.abbr}`, 0.06 * (0.85 + leader.energy / 300));
      break;
    }
    case "rally": {
      if (!region) return;
      res.actions -= 1;
      region.momentum = clamp(region.momentum + 6, -100, 100);
      res.momentum = clamp(res.momentum + 2, -100, 100);
      addAppeal(g, region, a.party, `${leader.name} rally in ${region.abbr}`, 0.045 * skill);
      break;
    }
    case "surrogate": {
      if (!region) return;
      if (!spend(0.25)) return;
      res.actions -= 1;
      addAppeal(g, region, a.party, `Surrogate stumps for ${leader.name} in ${region.abbr}`, 0.035 * (0.85 + leader.energy / 300));
      break;
    }
    case "broadcast": {
      const cost = Math.max(0.5, a.spend ?? 1.5);
      if (!spend(cost)) return;
      res.actions -= 1;
      const mode = a.mode ?? "positive";
      const targets = region ? [region] : standsIn(g, a.party);
      const power = 0.02 * Math.sqrt(cost / 1.5) * (0.85 + leader.machine / 300);
      const per = region ? power : power * 0.8;
      if (mode === "issue" && a.issueId) {
        g.salience[a.issueId] = clamp((g.salience[a.issueId] ?? 0.4) + 0.05, 0, 1);
        for (const t of targets) addAppeal(g, t, a.party, `${leader.name} issue broadcast`, per * 0.7);
      } else if (mode === "contrast") {
        for (const t of targets) {
          const foe = a.targetParty ?? topRivalIn(t, a.party);
          if (foe) addAppeal(g, t, foe, `${leader.name} contrast broadcast`, -per * 0.9);
        }
      } else {
        for (const t of targets) addAppeal(g, t, a.party, `${leader.name} broadcast`, per);
      }
      res.momentum = clamp(res.momentum + 1, -100, 100);
      break;
    }
    case "oppo_research": {
      if (!spend(2)) return;
      res.actions -= 1;
      const scope = region ? [region] : standsIn(g, a.party);
      for (const t of scope) {
        const foe = a.targetParty ?? topRivalIn(t, a.party);
        if (foe) addAppeal(g, t, a.party === foe ? a.party : foe, `${leader.name}'s team releases dossier on ${foe.toUpperCase()}`, -0.05 * compSkill);
      }
      break;
    }
    case "debate_prep": {
      res.actions -= 1;
      for (const t of standsIn(g, a.party)) addAppeal(g, t, a.party, `${leader.name} debate performance`, 0.012 * compSkill);
      res.momentum = clamp(res.momentum + 4, -100, 100);
      break;
    }
    case "policy_prep": {
      res.actions -= 1;
      for (const t of standsIn(g, a.party)) addAppeal(g, t, a.party, `${leader.name} platform launch`, 0.014 * compSkill);
      res.momentum = clamp(res.momentum + 2, -100, 100);
      break;
    }
    case "issue_pivot": {
      res.actions -= 1;
      if (a.issueId) g.salience[a.issueId] = clamp((g.salience[a.issueId] ?? 0.4) + 0.08, 0, 1);
      for (const t of standsIn(g, a.party)) addAppeal(g, t, a.party, `${leader.name} pivots the campaign`, 0.008 * skill);
      break;
    }
    case "fundraise": {
      res.actions -= 1;
      const haul = (1.5 + leader.machine / 50) * (0.85 + rng.next() * 0.3);
      res.funds += haul;
      g.causes.push({ turn: g.turn, cause: `${leader.name} fundraising (+${haul.toFixed(1)}M)`, marginDelta: 0 });
      break;
    }
  }
}

// ── AI + events + turn loop (country-parameterized) ────────────────────────
function planAiActions(g: CountryGameState, country: CountryBundle, party: PartyId, rng: Rng): CountryAction[] {
  const res = g.resources[party];
  const difficulty = (g.difficulty ?? "normal") as MpDifficulty;
  return planMultipartyAi(
    {
      regions: g.regions,
      turn: g.turn,
      totalTurns: g.totalTurns,
      funds: res.funds,
      actions: res.actions,
      majority: majorityFor(g, country),
      abstaining: g.abstaining,
      compatible: country.compatible,
    },
    party,
    difficulty,
    rng,
  ) as CountryAction[];
}

function pickEventTarget(
  role: CountryEventRole,
  player: PartyId,
  leader: PartyId,
  majors: PartyId[],
  pick: (xs: PartyId[]) => PartyId,
): PartyId {
  switch (role) {
    case "player": return player;
    case "leader": return leader;
    case "challenger": return pick(majors.filter((p) => p !== leader)) ?? player;
    default: return pick(majors) ?? player;
  }
}

function countryEventById(country: CountryBundle, g: CountryGameState, id: string): CountryEventDef | undefined {
  const deck = country.elections[g.electionId]?.events ?? [];
  return deck.find((e) => e.id === id) ?? country.events.find((e) => e.id === id);
}

function applyAppealNational(g: CountryGameState, target: PartyId, appeal: number, cause: string) {
  for (const region of g.regions) {
    if (region.baselineShare?.[target] === undefined) continue;
    for (const bloc of region.blocs) {
      if (!bloc.campaignAppeal) bloc.campaignAppeal = {};
      bloc.campaignAppeal[target] = (bloc.campaignAppeal[target] ?? 0) + appeal;
    }
  }
  g.causes.push({ turn: g.turn, cause, marginDelta: appeal });
}

function applyCountryEventEffects(g: CountryGameState, country: CountryBundle, ev: CountryEventDef, target: PartyId) {
  if (ev.appeal) applyAppealNational(g, target, ev.appeal, `${ev.id}: ${target.toUpperCase()}`);
  if (ev.momentum && g.resources[target]) {
    g.resources[target].momentum = clamp(g.resources[target].momentum + ev.momentum, -100, 100);
  }
  const short = country.system.parties.find((p) => p.id === target)?.shortName ?? target.toUpperCase();
  g.news = [{ turn: g.turn, text: ev.headline.replace("{party}", short) }, ...g.news].slice(0, 12);
}

function resolveCountryEventTarget(g: CountryGameState, country: CountryBundle, ev: CountryEventDef, rng: Rng): PartyId | undefined {
  const proj = computeSeatsResult(g.regions, majorityFor(g, country), g.abstaining);
  const majors = g.parties.filter((p) => country.playable.includes(p));
  return ev.party && g.parties.includes(ev.party)
    ? ev.party
    : pickEventTarget(ev.role, g.playerParty, proj.largestParty, majors, (xs) => rng.pick(xs));
}

function applyCountryEvent(g: CountryGameState, country: CountryBundle, ev: CountryEventDef, rng: Rng) {
  const target = resolveCountryEventTarget(g, country, ev, rng);
  if (!target) return;

  if (ev.choices && ev.choices.length > 0 && target === g.playerParty && !g.pendingEvent) {
    g.pendingEvent = { eventId: ev.id, targetParty: target };
    const short = country.system.parties.find((p) => p.id === target)?.shortName ?? target.toUpperCase();
    g.news = [{ turn: g.turn, text: ev.headline.replace("{party}", short) }, ...g.news].slice(0, 12);
    return;
  }
  applyCountryEventEffects(g, country, ev, target);
}

/** Resolve a pending player-choice event. Pure: returns a new game state. */
export function resolveCountryPlayerEvent(g: CountryGameState, country: CountryBundle, choiceId: string): CountryGameState {
  const next = structuredClone(g);
  const pending = next.pendingEvent;
  if (!pending) return next;
  const ev = countryEventById(country, next, pending.eventId);
  next.pendingEvent = null;
  if (!ev?.choices) return next;
  const choice = ev.choices.find((c) => c.id === choiceId) ?? ev.choices[0];
  const target = pending.targetParty;
  if (choice.appeal) applyAppealNational(next, target, choice.appeal, `${ev.id}: ${choice.text}`);
  if (choice.momentum && next.resources[target]) {
    next.resources[target].momentum = clamp(next.resources[target].momentum + choice.momentum, -100, 100);
  }
  if (choice.rivalAppeal) {
    const maj = majorityFor(next, country);
    const proj = computeSeatsResult(next.regions, maj, next.abstaining);
    const rival = Object.keys(proj.seats)
      .filter((p) => p !== target)
      .sort((a, b) => (proj.seats[b] ?? 0) - (proj.seats[a] ?? 0))[0] as PartyId | undefined;
    if (rival) applyAppealNational(next, rival, choice.rivalAppeal, `${ev.id}: hit on ${rival.toUpperCase()}`);
  }
  const short = country.system.parties.find((p) => p.id === target)?.shortName ?? target;
  next.lastRecap = [
    { label: ev.headline.replace("{party}", short), detail: choice.resultText, marginDelta: choice.appeal },
    ...(next.lastRecap ?? []),
  ].slice(0, 12);
  if (next.turn >= next.totalTurns) {
    next.phase = "result";
    next.result = computeCountryResult(next, country);
  }
  return next;
}

function fireCountryEvent(g: CountryGameState, country: CountryBundle, rng: Rng) {
  if (!g.firedEvents) g.firedEvents = []; // saves predating election decks
  const firedList = g.firedEvents;
  const fired = new Set(firedList);
  const deck = country.elections[g.electionId]?.events ?? [];

  for (const ev of deck) {
    if (ev.turn === undefined || ev.turn !== g.turn || fired.has(ev.id)) continue;
    applyCountryEvent(g, country, ev, rng);
    fired.add(ev.id);
    firedList.push(ev.id);
  }

  if (g.pendingEvent) return;

  const pool = [
    ...deck.filter((e) => e.turn === undefined && !fired.has(e.id)),
    ...country.events,
  ];
  if (pool.length === 0 || !rng.chance(country.eventChance)) return;
  const ev = rng.weightedPick(pool, pool.map((e) => e.weight));
  applyCountryEvent(g, country, ev, rng);
  if (deck.some((d) => d.id === ev.id)) firedList.push(ev.id);
}

function buildCountryRecap(g: CountryGameState, country: CountryBundle, turn: number, seatsBefore: number) {
  const seatsAfter = computeCountryResult(g, country).seats[g.playerParty] ?? 0;
  const short = country.system.parties.find((p) => p.id === g.playerParty)?.shortName ?? g.playerParty;
  return buildCauseRecap(
    g.causes,
    turn,
    {
      label: `Projected ${country.unitNamePlural}`,
      detail: `${short} ${seatsAfter} (was ${seatsBefore})`,
      marginDelta: seatsAfter - seatsBefore,
    },
  );
}

export interface CountryAdvanceOptions {
  disableAi?: boolean; // calibration anchor: neutral play reproduces history
  autoResolvePlayerEvents?: boolean;
}

export function countryAdvanceTurn(g: CountryGameState, country: CountryBundle, opts: CountryAdvanceOptions = {}): CountryGameState {
  let next: CountryGameState = structuredClone(g);
  const gate = resolvePendingChoiceGate(
    next,
    opts,
    (game, choiceId) => resolveCountryPlayerEvent(game, country, choiceId),
    (game) => {
      const ev = game.pendingEvent ? countryEventById(country, game, game.pendingEvent.eventId) : undefined;
      return ev?.choices?.[0]?.id;
    },
  );
  if (gate.blocked) return g;
  next = gate.game;

  if (next.phase === "result") return next;
  if (next.turn >= next.totalTurns) {
    next.phase = "result";
    next.result = computeCountryResult(next, country);
    return next;
  }

  const rng = createRng(next.rngState);
  const seatsBefore = computeCountryResult(next, country).seats[next.playerParty] ?? 0;
  const turn = next.turn;

  for (const a of next.queuedActions) applyCountryAction(next, a, rng);
  next.queuedActions = [];

  if (!opts.disableAi) {
    for (const p of next.parties) {
      if (p === next.playerParty || !country.playable.includes(p)) continue;
      for (const a of planAiActions(next, country, p, rng)) applyCountryAction(next, a, rng);
    }
    fireCountryEvent(next, country, rng);
  }

  decayMultipartyTurn(next.resources, next.regions, next.parties);

  next.lastRecap = buildCountryRecap(next, country, turn, seatsBefore);
  next.rngState = rng.state();
  return finalizeMpCampaignTurn(next, (game) => computeCountryResult(game, country));
}

export function computeCountryResult(g: CountryGameState, country: CountryBundle): CountryResult {
  const r = computeSeatsResult(g.regions, majorityFor(g, country), g.abstaining, country.compatible);
  const playerName = g.leaders[g.playerParty]?.name ?? "";
  const mine = g.causes.filter((c) => c.marginDelta !== 0 && c.cause.includes(playerName));
  const pool = mine.length > 0 ? mine : g.causes.filter((c) => c.marginDelta !== 0);
  const postMortem = [...pool]
    .sort((a, b) => Math.abs(b.marginDelta) - Math.abs(a.marginDelta))
    .slice(0, 8);
  return { ...r, postMortem };
}

export function projectCountry(g: CountryGameState, country: CountryBundle): CountryResult {
  return computeCountryResult(g, country);
}

export function projectCountryPreview(g: CountryGameState, country: CountryBundle): CountryResult {
  if (g.queuedActions.length === 0) return computeCountryResult(g, country);
  const clone = structuredClone(g);
  const rng = createRng(clone.rngState);
  for (const a of clone.queuedActions) applyCountryAction(clone, a, rng);
  for (const region of clone.regions)
    for (const bloc of region.blocs) bloc.support = blocPartyShares(bloc) as typeof bloc.support;
  return computeCountryResult(clone, country);
}
