import type { GameEvent } from "@engine/types";

// Per-scenario HISTORICAL event decks + a year-agnostic debate pair for the
// "plausible / random" mode. Like content/events.ts, these are pure data: each
// choice's bloc margins are in the *answering* candidate's favor (the engine
// flips the sign for whichever ticket answers), so a historical moment plays as
// "how does your campaign handle this beat" for either side.
//
// Magnitudes mirror events.ts (~0.03–0.06 margin is meaningful, not decisive).

// ── Generic debates (plausible mode, any year) ────────────────────────────
export const GENERIC_DEBATES: GameEvent[] = [
  {
    id: "gen_debate_1",
    title: "The First Presidential Debate",
    prompt: "Tens of millions tune in for the first face-off. The whole race can move in ninety minutes. How do you play the biggest stage you'll get?",
    subject: "both", isDebate: true, oncePerGame: true,
    trigger: { kind: "scheduled", turn: 4 },
    choices: [
      { id: "presidential", text: "Calm and presidential — talk past your opponent to the camera.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "seniors", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.01 }], momentum: 7, narrative: 9 },
        resultText: "You stay above the fray. The split-screen does the work — steady, reassuring." },
      { id: "aggressive", text: "Go on the attack — dominate every exchange.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05, enthusiasm: 0.02 }, { blocId: "youth", margin: 0.02 }, { blocId: "suburban_women", margin: -0.04 }], momentum: 4, narrative: -5 },
        resultText: "You fire up the base, but the crosstalk reads as a mess to voters at home." },
      { id: "wonk", text: "Win on substance — bury them in policy detail.", requires: { trait: "policyKnowledge", min: 72 },
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.06 }, { blocId: "seniors", margin: 0.02 }], salienceDeltas: { healthcare: 0.03 }, momentum: 5, narrative: 4 },
        resultText: "Command of detail wins the fact-checkers. A touch clinical for some." },
    ],
  },
  {
    id: "gen_debate_2",
    title: "The Final Debate",
    prompt: "The last debate before Election Day. The undecideds who are left are watching for one reason to break. Make your closing case.",
    subject: "both", isDebate: true, oncePerGame: true,
    trigger: { kind: "scheduled", turn: 7 },
    choices: [
      { id: "closing_unity", text: "A hopeful closing argument — turn the page.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }], momentum: 6, narrative: 7 },
        resultText: "You end on a high note. The closing montage practically writes itself." },
      { id: "closing_contrast", text: "Draw the contrast hard — make it a choice, not a referendum.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "seniors", margin: 0.03 }, { blocId: "youth", margin: -0.02 }], momentum: 5, narrative: 0 },
        resultText: "You sharpen the stakes. Your base is energized; a few swing voters tire of the negativity." },
    ],
  },
];

// ── 2016 · Clinton v. Trump ───────────────────────────────────────────────
export const HIST_2016: GameEvent[] = [
  { id: "h16_deplorables", title: "A Fundraiser Line Goes Viral", subject: "both", oncePerGame: true,
    prompt: "A blunt remark about the other side's supporters leaks from a closed-door fundraiser. The clip is everywhere by morning. Do you stand by it or walk it back?",
    trigger: { kind: "scheduled", turn: 0 },
    choices: [
      { id: "stand", text: "Stand by it — your base loves the candor.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.04 }, { blocId: "youth", margin: 0.03 }, { blocId: "noncollege_white", margin: -0.05 }], momentum: 3, narrative: -4 },
        resultText: "The base roars, but the clip becomes a recruiting tool for the other side." },
      { id: "walk", text: "Walk it back — say you regret the generalization.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: 0.03 }], momentum: 1, narrative: 3 },
        resultText: "The cleanup holds. Cable moves on by the weekend." },
    ] },
  { id: "h16_health", title: "A Health Scare on the Trail", subject: "both", oncePerGame: true,
    prompt: "A near-collapse at a memorial event — caught on a bystander's phone — sets off a frenzy about stamina and what the campaign isn't saying. How do you answer?",
    trigger: { kind: "scheduled", turn: 1 },
    choices: [
      { id: "records", text: "Release detailed medical records and get back out fast.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.05 }, { blocId: "suburban_women", margin: 0.03 }], momentum: 4, narrative: 5 },
        resultText: "Transparency defuses it. A brisk rally swing puts the stamina story to bed." },
      { id: "powerthrough", text: "Power through — pack the schedule and say nothing.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03 }, { blocId: "seniors", margin: -0.03 }], momentum: 2, narrative: -3 },
        resultText: "You project toughness, but the silence lets the speculation run another week." },
    ] },
  { id: "h16_debate1", title: "First Debate (Hofstra)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "The most-watched debate in history. One of you is over-prepared, one is winging it. Ninety minutes to define the race.",
    trigger: { kind: "scheduled", turn: 2 },
    choices: [
      { id: "bait", text: "Set traps — bait your opponent into an unforced error.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.05 }, { blocId: "suburban_women", margin: 0.05 }, { blocId: "noncollege_white", margin: -0.02 }], momentum: 6, narrative: 8 },
        resultText: "The traps spring. The post-debate clips run against your opponent for days." },
      { id: "punch", text: "Throw haymakers — never concede a point.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05, enthusiasm: 0.02 }, { blocId: "suburban_women", margin: -0.04 }], momentum: 3, narrative: -4 },
        resultText: "The base is thrilled; suburban viewers are exhausted." },
    ] },
  { id: "h16_tape", title: "An 'Access Hollywood' Bombshell", subject: "both", oncePerGame: true,
    prompt: "A decade-old hot-mic recording surfaces a month out, and it is ugly. Down-ballot allies are running for the exits. This is the hinge of the whole campaign.",
    trigger: { kind: "scheduled", turn: 4 },
    choices: [
      { id: "capitalize", text: "Capitalize — cut a contrast ad tonight and let it breathe.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.07 }, { blocId: "college_white", margin: 0.05 }, { blocId: "noncollege_white", margin: -0.01 }], momentum: 8, narrative: 9 },
        resultText: "You let the tape do the talking. Suburban women break hard your way." },
      { id: "apologize", text: "Apologize, contain the damage, and counterpunch.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03, enthusiasm: 0.02 }, { blocId: "suburban_women", margin: -0.06 }, { blocId: "seniors", margin: -0.03 }], momentum: -4, narrative: -6 },
        resultText: "The base sticks, but the bleeding with women and seniors doesn't fully stop." },
      { id: "dismiss", text: "Dismiss it as a distraction and change the subject.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.02 }, { blocId: "suburban_women", margin: -0.07 }], momentum: -5, narrative: -8 },
        resultText: "The 'distraction' framing collapses on contact. The story runs for two weeks." },
    ] },
  { id: "h16_debate3", title: "Final Debate (Las Vegas)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "Last debate. A loaded question about accepting the result of the election hangs in the air. Your answer will be the headline.",
    trigger: { kind: "scheduled", turn: 6 },
    choices: [
      { id: "respect", text: "Pledge to respect the result, whatever it is.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "seniors", margin: 0.04 }], momentum: 5, narrative: 7 },
        resultText: "Reassuring to the middle. The clip ages well." },
      { id: "suspense", text: "Keep them in suspense — 'I'll let you know.'",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04, enthusiasm: 0.02 }, { blocId: "college_white", margin: -0.05 }], momentum: 2, narrative: -6 },
        resultText: "The base eats it up; the press calls it unprecedented for a week." },
    ] },
  { id: "h16_letter", title: "The Bureau Reopens an Investigation", subject: "both", oncePerGame: true,
    prompt: "Eleven days out, a law-enforcement letter to Congress reopens a closed investigation. No new facts — just a cloud, at the worst possible moment. How do you play it?",
    trigger: { kind: "scheduled", turn: 7 },
    choices: [
      { id: "amplify", text: "Amplify it — make it the closing argument.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "seniors", margin: 0.04 }, { blocId: "college_white", margin: -0.01 }], momentum: 6, narrative: 4 },
        resultText: "The cloud does your closing work for you. Undecideds wobble." },
      { id: "fight", text: "Fight the process — demand they release everything now.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.04 }, { blocId: "suburban_women", margin: 0.02 }], momentum: 1, narrative: 2 },
        resultText: "You blunt it, but the story still dominates a precious final week." },
      { id: "ignore", text: "Ignore it — keep relentlessly on your own message.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.03 }, { blocId: "noncollege_white", margin: -0.02 }], momentum: 0, narrative: 1 },
        resultText: "Discipline keeps you on offense, but the cloud lingers in the background." },
    ] },
];

// ── 2024 · Harris v. Trump ────────────────────────────────────────────────
export const HIST_2024: GameEvent[] = [
  { id: "h24_switch", title: "A New Nominee, A Convention Surge", subject: "both", oncePerGame: true,
    prompt: "A late, dramatic shake-up at the top of the ticket has remade the race overnight. Small-dollar money and volunteers are pouring in. How do you ride the wave?",
    trigger: { kind: "scheduled", turn: 0 },
    choices: [
      { id: "joy", text: "Lean into the momentum — a joyful, forward-looking blitz.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.06 }, { blocId: "black", margin: 0.04 }, { blocId: "suburban_women", margin: 0.04 }], cash: 9_000_000, momentum: 7, narrative: 6 },
        resultText: "The energy is real. Rallies overflow and the money keeps coming." },
      { id: "steady", text: "Steady the ship — reassure nervous moderates and donors.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.04 }, { blocId: "college_white", margin: 0.04 }], cash: 5_000_000, momentum: 4, narrative: 4 },
        resultText: "You bank the bounce and lock down the center. Less spectacle, more durability." },
    ] },
  { id: "h24_border", title: "A Small Town in the Spotlight", subject: "both", oncePerGame: true,
    prompt: "A viral, unfounded rumor about immigrants in a Midwestern town explodes online and gets repeated on a debate stage. Immigration is suddenly the only story. How do you handle it?",
    trigger: { kind: "scheduled", turn: 1 },
    choices: [
      { id: "factcheck", text: "Fact-check hard and pivot to a real border plan.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "hispanic", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.02 }], salienceDeltas: { immigration: 0.04 }, momentum: 3, narrative: 4 },
        resultText: "The debunk lands with the middle; the base of the other side digs in." },
      { id: "hammer", text: "Hammer the border as a failure of the other side.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06 }, { blocId: "seniors", margin: 0.03 }, { blocId: "hispanic", margin: -0.03 }], salienceDeltas: { immigration: 0.06 }, momentum: 4, narrative: -2 },
        resultText: "Immigration salience spikes — great for your base, a turnoff for some Latino voters." },
    ] },
  { id: "h24_debate", title: "The Prime-Time Debate", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "A single, high-stakes prime-time debate. The whole campaign has been waiting for this one matchup. Set the terms.",
    trigger: { kind: "scheduled", turn: 2 },
    choices: [
      { id: "bait", text: "Bait the temper — get under your opponent's skin on crowd size and grievance.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.06 }, { blocId: "college_white", margin: 0.05 }, { blocId: "noncollege_white", margin: -0.02 }], momentum: 6, narrative: 8 },
        resultText: "The bait works. Your opponent spends ninety minutes defending the indefensible." },
      { id: "economy", text: "Stay laser-focused on prices and the cost of living.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "hispanic", margin: 0.03 }], salienceDeltas: { economy: 0.05 }, momentum: 4, narrative: 2 },
        resultText: "Disciplined and on-message — you win the voters who only care about their wallet." },
    ] },
  { id: "h24_security", title: "A Security Scare", subject: "both", oncePerGame: true,
    prompt: "A frightening security incident on the trail rattles the country and freezes the campaign for forty-eight hours. The tone of the race is yours to set now.",
    trigger: { kind: "scheduled", turn: 3 },
    choices: [
      { id: "unity", text: "Call for unity and turn down the temperature.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "seniors", margin: 0.05 }], momentum: 4, narrative: 6 },
        resultText: "A steady, unifying note plays well with a jittery middle." },
      { id: "resolve", text: "Project defiance and resolve — never back down.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06, enthusiasm: 0.03 }, { blocId: "suburban_women", margin: -0.02 }], momentum: 5, narrative: 1 },
        resultText: "The image of defiance becomes an instant rallying icon for your base." },
    ] },
  { id: "h24_economy", title: "The Closing Argument: Prices vs. Freedom", subject: "both", oncePerGame: true,
    prompt: "The campaign narrows to two questions: can you afford your life, and who do you trust with your rights? You can only headline one. Which closing argument?",
    trigger: { kind: "scheduled", turn: 5 },
    choices: [
      { id: "rights", text: "Make it about rights and democracy.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.06 }, { blocId: "youth", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }], salienceDeltas: { abortion: 0.05 }, momentum: 5, narrative: 4 },
        resultText: "You consolidate the coalition that turned out on rights — but cede the economy frame." },
      { id: "prices", text: "Make it about prices and the economy.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06 }, { blocId: "hispanic", margin: 0.04 }, { blocId: "youth", margin: -0.01 }], salienceDeltas: { economy: 0.06 }, momentum: 5, narrative: 3 },
        resultText: "Kitchen-table economics wins the persuadables who decide late." },
    ] },
  { id: "h24_rally", title: "A Rally Remark Goes Sideways", subject: "both", oncePerGame: true,
    prompt: "A headline rally produces an ugly insult — and then a clumsy response from the other side hands it right back. Both campaigns are suddenly playing defense. How do you spin the week?",
    trigger: { kind: "scheduled", turn: 6 },
    choices: [
      { id: "contrast", text: "Draw a sharp contrast and stay disciplined.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "hispanic", margin: 0.04 }], momentum: 4, narrative: 4 },
        resultText: "You rise above the food fight and let your opponent own the mess." },
      { id: "feed", text: "Feed the outrage cycle — keep it the story.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04, enthusiasm: 0.02 }, { blocId: "college_white", margin: -0.03 }], momentum: 2, narrative: -3 },
        resultText: "The base is fired up, but the endless outrage loop turns off the tired middle." },
    ] },
];

// ── 2000 · Gore v. Bush ───────────────────────────────────────────────────
export const HIST_2000: GameEvent[] = [
  { id: "h00_convention", title: "Convention Bounce", subject: "both", oncePerGame: true,
    prompt: "Peace and prosperity, a budget surplus, and a country that mostly likes the status quo. Your convention lands a bounce. How do you spend it?",
    trigger: { kind: "scheduled", turn: 0 },
    choices: [
      { id: "continuity", text: "Run on continuity and competence — don't rock the boat.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.05 }, { blocId: "college_white", margin: 0.03 }], momentum: 4, narrative: 4 },
        resultText: "Steady-as-she-goes reassures a contented electorate." },
      { id: "change", text: "Run as a fresh start — a change of tone in Washington.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04 }, { blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: -0.02 }], momentum: 4, narrative: 3 },
        resultText: "The change message excites the persuadables who are bored of the incumbents." },
    ] },
  { id: "h00_debate1", title: "First Debate (Boston)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "The first debate. One of you risks looking like a know-it-all; the other risks looking out of his depth. Mannerisms will matter as much as substance.",
    trigger: { kind: "scheduled", turn: 2 },
    choices: [
      { id: "command", text: "Command the substance — bury them in policy.", requires: { trait: "policyKnowledge", min: 70 },
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.05 }, { blocId: "seniors", margin: 0.03 }, { blocId: "noncollege_white", margin: -0.03 }], momentum: 4, narrative: 2 },
        resultText: "You win on points — but the sighing and eye-rolling become the story." },
      { id: "likeable", text: "Play it warm and likeable — connect, don't lecture.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "suburban_women", margin: 0.04 }], momentum: 5, narrative: 5 },
        resultText: "Affable beats encyclopedic. The 'who'd you rather have a beer with' crowd warms to you." },
    ] },
  { id: "h00_vpdebate", title: "A Cordial VP Debate", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "An unusually civil, substantive undercard debate. No fireworks — just two running mates making the case. Whose ticket does it help?",
    trigger: { kind: "scheduled", turn: 3 },
    choices: [
      { id: "gravitas", text: "Sell experience and a steady hand.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.04 }, { blocId: "college_white", margin: 0.03 }], momentum: 3, narrative: 3 },
        resultText: "The grown-up tone reassures voters worried about the top of the ticket." },
      { id: "future", text: "Sell freshness and the next generation.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.04 }, { blocId: "suburban_women", margin: 0.03 }], momentum: 3, narrative: 2 },
        resultText: "A forward-looking pitch nudges younger and suburban voters your way." },
    ] },
  { id: "h00_townhall", title: "The Town-Hall Debate", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "A town-hall format with undecided voters in the room. Body language is everything — one awkward move can define you.",
    trigger: { kind: "scheduled", turn: 5 },
    choices: [
      { id: "connect", text: "Work the room — empathy and eye contact.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "black", margin: 0.03 }], momentum: 4, narrative: 4 },
        resultText: "You connect with the room. The reaction shots all break your way." },
      { id: "loom", text: "Assert dominance — crowd the stage and your opponent.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03 }, { blocId: "suburban_women", margin: -0.05 }], momentum: 1, narrative: -4 },
        resultText: "The move reads as aggressive and odd. The clip loops for days." },
    ] },
  { id: "h00_ads", title: "A Subliminal-Ad Flap", subject: "both", oncePerGame: true,
    prompt: "A single frame of an attack ad is caught flashing a loaded word for a thirtieth of a second. It's silly — and it's leading every newscast. How do you respond?",
    trigger: { kind: "scheduled", turn: 6 },
    choices: [
      { id: "laugh", text: "Laugh it off and pull the ad.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.03 }, { blocId: "suburban_women", margin: 0.02 }], momentum: 1, narrative: 2 },
        resultText: "A light touch makes the story evaporate by the weekend." },
      { id: "deny", text: "Deny everything and keep the ad running.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.02 }, { blocId: "college_white", margin: -0.03 }], momentum: 0, narrative: -3 },
        resultText: "The denial keeps the silly story alive for an extra week of free coverage." },
    ] },
  { id: "h00_dui", title: "An Eleventh-Hour Revelation", subject: "both", oncePerGame: true,
    prompt: "Days before the vote, a decades-old arrest record surfaces and dominates the final weekend. It's old news, but the timing is brutal. How do you close?",
    trigger: { kind: "scheduled", turn: 7 },
    choices: [
      { id: "honest", text: "Get ahead of it — own it, be honest, move on.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: 0.03 }], momentum: 3, narrative: 4 },
        resultText: "Candor blunts the hit. Voters respect the straight answer in the final hours." },
      { id: "exploit", text: "Exploit it — question their character to the last.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04 }, { blocId: "seniors", margin: 0.03 }, { blocId: "youth", margin: -0.02 }], momentum: 3, narrative: -1 },
        resultText: "The character hit lands with some — but late mud splashes back on you, too." },
    ] },
];
