import type { GameEvent } from "@engine/types";

// Per-scenario HISTORICAL event decks + a year-agnostic debate pair for the
// "plausible / random" mode. Like content/events.ts, these are pure data: each
// choice's bloc margins are in the *answering* candidate's favor (the engine
// flips the sign for whichever ticket answers), so a historical moment plays as
// "how does your campaign handle this beat" for either side.
//
// Magnitudes mirror events.ts (~0.03–0.06 margin is meaningful, not decisive).

// ── Generic debates (plausible mode, any year) ────────────────────────────
export const GENERIC_DEBATES: GameEvent[] = [
  {
    id: "gen_debate_1",
    title: "The First Presidential Debate",
    prompt: "Tens of millions tune in for the first face-off. The whole race can move in ninety minutes. How do you play the biggest stage you'll get?",
    subject: "both", isDebate: true, oncePerGame: true,
    trigger: { kind: "scheduled", turn: 4 },
    choices: [
      { id: "presidential", text: "Calm and presidential — talk past your opponent to the camera.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "seniors", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.01 }], momentum: 7, narrative: 9 },
        resultText: "You stay above the fray. The split-screen does the work — steady, reassuring." },
      { id: "aggressive", text: "Go on the attack — dominate every exchange.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05, enthusiasm: 0.02 }, { blocId: "youth", margin: 0.02 }, { blocId: "suburban_women", margin: -0.04 }], momentum: 4, narrative: -5 },
        resultText: "You fire up the base, but the crosstalk reads as a mess to voters at home." },
      { id: "wonk", text: "Win on substance — bury them in policy detail.", requires: { trait: "policyKnowledge", min: 72 },
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.06 }, { blocId: "seniors", margin: 0.02 }], salienceDeltas: { healthcare: 0.03 }, momentum: 5, narrative: 4 },
        resultText: "Command of detail wins the fact-checkers. A touch clinical for some." },
    ],
  },
  {
    id: "gen_debate_2",
    title: "The Final Debate",
    prompt: "The last debate before Election Day. The undecideds who are left are watching for one reason to break. Make your closing case.",
    subject: "both", isDebate: true, oncePerGame: true,
    trigger: { kind: "scheduled", turn: 7 },
    choices: [
      { id: "closing_unity", text: "A hopeful closing argument — turn the page.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }], momentum: 6, narrative: 7 },
        resultText: "You end on a high note. The closing montage practically writes itself." },
      { id: "closing_contrast", text: "Draw the contrast hard — make it a choice, not a referendum.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "seniors", margin: 0.03 }, { blocId: "youth", margin: -0.02 }], momentum: 5, narrative: 0 },
        resultText: "You sharpen the stakes. Your base is energized; a few swing voters tire of the negativity." },
    ],
  },
];

// ── 2016 · Clinton v. Trump ───────────────────────────────────────────────
export const HIST_2016: GameEvent[] = [
  { id: "h16_deplorables", title: "A Fundraiser Line Goes Viral", subject: "both", oncePerGame: true,
    prompt: "A blunt remark about the other side's supporters leaks from a closed-door fundraiser. The clip is everywhere by morning. Do you stand by it or walk it back?",
    trigger: { kind: "scheduled", turn: 0 },
    choices: [
      { id: "stand", text: "Stand by it — your base loves the candor.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.04 }, { blocId: "youth", margin: 0.03 }, { blocId: "noncollege_white", margin: -0.05 }], momentum: 3, narrative: -4 },
        resultText: "The base roars, but the clip becomes a recruiting tool for the other side." },
      { id: "walk", text: "Walk it back — say you regret the generalization.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: 0.03 }], momentum: 1, narrative: 3 },
        resultText: "The cleanup holds. Cable moves on by the weekend." },
    ] },
  { id: "h16_health", title: "A Health Scare on the Trail", subject: "both", oncePerGame: true,
    prompt: "A near-collapse at a memorial event — caught on a bystander's phone — sets off a frenzy about stamina and what the campaign isn't saying. How do you answer?",
    trigger: { kind: "scheduled", turn: 1 },
    choices: [
      { id: "records", text: "Release detailed medical records and get back out fast.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.05 }, { blocId: "suburban_women", margin: 0.03 }], momentum: 4, narrative: 5 },
        resultText: "Transparency defuses it. A brisk rally swing puts the stamina story to bed." },
      { id: "powerthrough", text: "Power through — pack the schedule and say nothing.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03 }, { blocId: "seniors", margin: -0.03 }], momentum: 2, narrative: -3 },
        resultText: "You project toughness, but the silence lets the speculation run another week." },
    ] },
  { id: "h16_debate1", title: "First Debate (Hofstra)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "The most-watched debate in history. One of you is over-prepared, one is winging it. Ninety minutes to define the race.",
    trigger: { kind: "scheduled", turn: 2 },
    choices: [
      { id: "bait", text: "Set traps — bait your opponent into an unforced error.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.05 }, { blocId: "suburban_women", margin: 0.05 }, { blocId: "noncollege_white", margin: -0.02 }], momentum: 6, narrative: 8 },
        resultText: "The traps spring. The post-debate clips run against your opponent for days." },
      { id: "punch", text: "Throw haymakers — never concede a point.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05, enthusiasm: 0.02 }, { blocId: "suburban_women", margin: -0.04 }], momentum: 3, narrative: -4 },
        resultText: "The base is thrilled; suburban viewers are exhausted." },
    ] },
  { id: "h16_tape", title: "An 'Access Hollywood' Bombshell", subject: "both", oncePerGame: true,
    prompt: "A decade-old hot-mic recording surfaces a month out, and it is ugly. Down-ballot allies are running for the exits. This is the hinge of the whole campaign.",
    trigger: { kind: "scheduled", turn: 4 },
    choices: [
      { id: "capitalize", text: "Capitalize — cut a contrast ad tonight and let it breathe.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.07 }, { blocId: "college_white", margin: 0.05 }, { blocId: "noncollege_white", margin: -0.01 }], momentum: 8, narrative: 9 },
        resultText: "You let the tape do the talking. Suburban women break hard your way." },
      { id: "apologize", text: "Apologize, contain the damage, and counterpunch.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03, enthusiasm: 0.02 }, { blocId: "suburban_women", margin: -0.06 }, { blocId: "seniors", margin: -0.03 }], momentum: -4, narrative: -6 },
        resultText: "The base sticks, but the bleeding with women and seniors doesn't fully stop." },
      { id: "dismiss", text: "Dismiss it as a distraction and change the subject.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.02 }, { blocId: "suburban_women", margin: -0.07 }], momentum: -5, narrative: -8 },
        resultText: "The 'distraction' framing collapses on contact. The story runs for two weeks." },
    ] },
  { id: "h16_debate3", title: "Final Debate (Las Vegas)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "Last debate. A loaded question about accepting the result of the election hangs in the air. Your answer will be the headline.",
    trigger: { kind: "scheduled", turn: 6 },
    choices: [
      { id: "respect", text: "Pledge to respect the result, whatever it is.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "seniors", margin: 0.04 }], momentum: 5, narrative: 7 },
        resultText: "Reassuring to the middle. The clip ages well." },
      { id: "suspense", text: "Keep them in suspense — 'I'll let you know.'",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04, enthusiasm: 0.02 }, { blocId: "college_white", margin: -0.05 }], momentum: 2, narrative: -6 },
        resultText: "The base eats it up; the press calls it unprecedented for a week." },
    ] },
  { id: "h16_letter", title: "The Bureau Reopens an Investigation", subject: "both", oncePerGame: true,
    prompt: "Eleven days out, a law-enforcement letter to Congress reopens a closed investigation. No new facts — just a cloud, at the worst possible moment. How do you play it?",
    trigger: { kind: "scheduled", turn: 7 },
    choices: [
      { id: "amplify", text: "Amplify it — make it the closing argument.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "seniors", margin: 0.04 }, { blocId: "college_white", margin: -0.01 }], momentum: 6, narrative: 4 },
        resultText: "The cloud does your closing work for you. Undecideds wobble." },
      { id: "fight", text: "Fight the process — demand they release everything now.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.04 }, { blocId: "suburban_women", margin: 0.02 }], momentum: 1, narrative: 2 },
        resultText: "You blunt it, but the story still dominates a precious final week." },
      { id: "ignore", text: "Ignore it — keep relentlessly on your own message.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.03 }, { blocId: "noncollege_white", margin: -0.02 }], momentum: 0, narrative: 1 },
        resultText: "Discipline keeps you on offense, but the cloud lingers in the background." },
    ] },
];

// ── 2024 · Harris v. Trump ────────────────────────────────────────────────
export const HIST_2024: GameEvent[] = [
  { id: "h24_switch", title: "A New Nominee, A Convention Surge", subject: "both", oncePerGame: true,
    prompt: "A late, dramatic shake-up at the top of the ticket has remade the race overnight. Small-dollar money and volunteers are pouring in. How do you ride the wave?",
    trigger: { kind: "scheduled", turn: 0 },
    choices: [
      { id: "joy", text: "Lean into the momentum — a joyful, forward-looking blitz.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.06 }, { blocId: "black", margin: 0.04 }, { blocId: "suburban_women", margin: 0.04 }], cash: 9_000_000, momentum: 7, narrative: 6 },
        resultText: "The energy is real. Rallies overflow and the money keeps coming." },
      { id: "steady", text: "Steady the ship — reassure nervous moderates and donors.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.04 }, { blocId: "college_white", margin: 0.04 }], cash: 5_000_000, momentum: 4, narrative: 4 },
        resultText: "You bank the bounce and lock down the center. Less spectacle, more durability." },
    ] },
  { id: "h24_border", title: "A Small Town in the Spotlight", subject: "both", oncePerGame: true,
    prompt: "A viral, unfounded rumor about immigrants in a Midwestern town explodes online and gets repeated on a debate stage. Immigration is suddenly the only story. How do you handle it?",
    trigger: { kind: "scheduled", turn: 1 },
    choices: [
      { id: "factcheck", text: "Fact-check hard and pivot to a real border plan.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "hispanic", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.02 }], salienceDeltas: { immigration: 0.04 }, momentum: 3, narrative: 4 },
        resultText: "The debunk lands with the middle; the base of the other side digs in." },
      { id: "hammer", text: "Hammer the border as a failure of the other side.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06 }, { blocId: "seniors", margin: 0.03 }, { blocId: "hispanic", margin: -0.03 }], salienceDeltas: { immigration: 0.06 }, momentum: 4, narrative: -2 },
        resultText: "Immigration salience spikes — great for your base, a turnoff for some Latino voters." },
    ] },
  { id: "h24_debate", title: "The Prime-Time Debate", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "A single, high-stakes prime-time debate. The whole campaign has been waiting for this one matchup. Set the terms.",
    trigger: { kind: "scheduled", turn: 2 },
    choices: [
      { id: "bait", text: "Bait the temper — get under your opponent's skin on crowd size and grievance.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.06 }, { blocId: "college_white", margin: 0.05 }, { blocId: "noncollege_white", margin: -0.02 }], momentum: 6, narrative: 8 },
        resultText: "The bait works. Your opponent spends ninety minutes defending the indefensible." },
      { id: "economy", text: "Stay laser-focused on prices and the cost of living.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "hispanic", margin: 0.03 }], salienceDeltas: { economy: 0.05 }, momentum: 4, narrative: 2 },
        resultText: "Disciplined and on-message — you win the voters who only care about their wallet." },
    ] },
  { id: "h24_security", title: "A Security Scare", subject: "both", oncePerGame: true,
    prompt: "A frightening security incident on the trail rattles the country and freezes the campaign for forty-eight hours. The tone of the race is yours to set now.",
    trigger: { kind: "scheduled", turn: 3 },
    choices: [
      { id: "unity", text: "Call for unity and turn down the temperature.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "seniors", margin: 0.05 }], momentum: 4, narrative: 6 },
        resultText: "A steady, unifying note plays well with a jittery middle." },
      { id: "resolve", text: "Project defiance and resolve — never back down.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06, enthusiasm: 0.03 }, { blocId: "suburban_women", margin: -0.02 }], momentum: 5, narrative: 1 },
        resultText: "The image of defiance becomes an instant rallying icon for your base." },
    ] },
  { id: "h24_economy", title: "The Closing Argument: Prices vs. Freedom", subject: "both", oncePerGame: true,
    prompt: "The campaign narrows to two questions: can you afford your life, and who do you trust with your rights? You can only headline one. Which closing argument?",
    trigger: { kind: "scheduled", turn: 5 },
    choices: [
      { id: "rights", text: "Make it about rights and democracy.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.06 }, { blocId: "youth", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }], salienceDeltas: { abortion: 0.05 }, momentum: 5, narrative: 4 },
        resultText: "You consolidate the coalition that turned out on rights — but cede the economy frame." },
      { id: "prices", text: "Make it about prices and the economy.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06 }, { blocId: "hispanic", margin: 0.04 }, { blocId: "youth", margin: -0.01 }], salienceDeltas: { economy: 0.06 }, momentum: 5, narrative: 3 },
        resultText: "Kitchen-table economics wins the persuadables who decide late." },
    ] },
  { id: "h24_rally", title: "A Rally Remark Goes Sideways", subject: "both", oncePerGame: true,
    prompt: "A headline rally produces an ugly insult — and then a clumsy response from the other side hands it right back. Both campaigns are suddenly playing defense. How do you spin the week?",
    trigger: { kind: "scheduled", turn: 6 },
    choices: [
      { id: "contrast", text: "Draw a sharp contrast and stay disciplined.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "hispanic", margin: 0.04 }], momentum: 4, narrative: 4 },
        resultText: "You rise above the food fight and let your opponent own the mess." },
      { id: "feed", text: "Feed the outrage cycle — keep it the story.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04, enthusiasm: 0.02 }, { blocId: "college_white", margin: -0.03 }], momentum: 2, narrative: -3 },
        resultText: "The base is fired up, but the endless outrage loop turns off the tired middle." },
    ] },
];

// ── 2000 · Gore v. Bush ───────────────────────────────────────────────────
export const HIST_2000: GameEvent[] = [
  { id: "h00_convention", title: "Convention Bounce", subject: "both", oncePerGame: true,
    prompt: "Peace and prosperity, a budget surplus, and a country that mostly likes the status quo. Your convention lands a bounce. How do you spend it?",
    trigger: { kind: "scheduled", turn: 0 },
    choices: [
      { id: "continuity", text: "Run on continuity and competence — don't rock the boat.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.05 }, { blocId: "college_white", margin: 0.03 }], momentum: 4, narrative: 4 },
        resultText: "Steady-as-she-goes reassures a contented electorate." },
      { id: "change", text: "Run as a fresh start — a change of tone in Washington.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04 }, { blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: -0.02 }], momentum: 4, narrative: 3 },
        resultText: "The change message excites the persuadables who are bored of the incumbents." },
    ] },
  { id: "h00_debate1", title: "First Debate (Boston)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "The first debate. One of you risks looking like a know-it-all; the other risks looking out of his depth. Mannerisms will matter as much as substance.",
    trigger: { kind: "scheduled", turn: 2 },
    choices: [
      { id: "command", text: "Command the substance — bury them in policy.", requires: { trait: "policyKnowledge", min: 70 },
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.05 }, { blocId: "seniors", margin: 0.03 }, { blocId: "noncollege_white", margin: -0.03 }], momentum: 4, narrative: 2 },
        resultText: "You win on points — but the sighing and eye-rolling become the story." },
      { id: "likeable", text: "Play it warm and likeable — connect, don't lecture.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "suburban_women", margin: 0.04 }], momentum: 5, narrative: 5 },
        resultText: "Affable beats encyclopedic. The 'who'd you rather have a beer with' crowd warms to you." },
    ] },
  { id: "h00_vpdebate", title: "A Cordial VP Debate", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "An unusually civil, substantive undercard debate. No fireworks — just two running mates making the case. Whose ticket does it help?",
    trigger: { kind: "scheduled", turn: 3 },
    choices: [
      { id: "gravitas", text: "Sell experience and a steady hand.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.04 }, { blocId: "college_white", margin: 0.03 }], momentum: 3, narrative: 3 },
        resultText: "The grown-up tone reassures voters worried about the top of the ticket." },
      { id: "future", text: "Sell freshness and the next generation.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.04 }, { blocId: "suburban_women", margin: 0.03 }], momentum: 3, narrative: 2 },
        resultText: "A forward-looking pitch nudges younger and suburban voters your way." },
    ] },
  { id: "h00_townhall", title: "The Town-Hall Debate", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "A town-hall format with undecided voters in the room. Body language is everything — one awkward move can define you.",
    trigger: { kind: "scheduled", turn: 5 },
    choices: [
      { id: "connect", text: "Work the room — empathy and eye contact.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "black", margin: 0.03 }], momentum: 4, narrative: 4 },
        resultText: "You connect with the room. The reaction shots all break your way." },
      { id: "loom", text: "Assert dominance — crowd the stage and your opponent.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03 }, { blocId: "suburban_women", margin: -0.05 }], momentum: 1, narrative: -4 },
        resultText: "The move reads as aggressive and odd. The clip loops for days." },
    ] },
  { id: "h00_ads", title: "A Subliminal-Ad Flap", subject: "both", oncePerGame: true,
    prompt: "A single frame of an attack ad is caught flashing a loaded word for a thirtieth of a second. It's silly — and it's leading every newscast. How do you respond?",
    trigger: { kind: "scheduled", turn: 6 },
    choices: [
      { id: "laugh", text: "Laugh it off and pull the ad.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.03 }, { blocId: "suburban_women", margin: 0.02 }], momentum: 1, narrative: 2 },
        resultText: "A light touch makes the story evaporate by the weekend." },
      { id: "deny", text: "Deny everything and keep the ad running.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.02 }, { blocId: "college_white", margin: -0.03 }], momentum: 0, narrative: -3 },
        resultText: "The denial keeps the silly story alive for an extra week of free coverage." },
    ] },
  { id: "h00_dui", title: "An Eleventh-Hour Revelation", subject: "both", oncePerGame: true,
    prompt: "Days before the vote, a decades-old arrest record surfaces and dominates the final weekend. It's old news, but the timing is brutal. How do you close?",
    trigger: { kind: "scheduled", turn: 7 },
    choices: [
      { id: "honest", text: "Get ahead of it — own it, be honest, move on.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: 0.03 }], momentum: 3, narrative: 4 },
        resultText: "Candor blunts the hit. Voters respect the straight answer in the final hours." },
      { id: "exploit", text: "Exploit it — question their character to the last.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04 }, { blocId: "seniors", margin: 0.03 }, { blocId: "youth", margin: -0.02 }], momentum: 3, narrative: -1 },
        resultText: "The character hit lands with some — but late mud splashes back on you, too." },
    ] },
];

// ── 2008 · Obama v. McCain ────────────────────────────────────────────────
export const HIST_2008: GameEvent[] = [
  { id: "h08_convention", title: "A Stadium Convention", subject: "both", oncePerGame: true,
    prompt: "A soaring, record-audience convention speech sets the tone. The energy is enormous — and so are the expectations. How do you ride it?",
    trigger: { kind: "scheduled", turn: 0 },
    choices: [
      { id: "hope", text: "Lean into hope and change — a generational pitch.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.06 }, { blocId: "black", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }], momentum: 6, narrative: 6 },
        resultText: "The movement swells. Young and first-time voters flood your volunteer rolls." },
      { id: "ready", text: "Reassure the middle — steady, ready on day one.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.05 }, { blocId: "suburban_women", margin: 0.04 }], momentum: 4, narrative: 4 },
        resultText: "You trade a little spectacle for gravitas. Nervous moderates exhale." },
    ] },
  { id: "h08_vp", title: "A Surprise on the Ticket", subject: "both", oncePerGame: true,
    prompt: "A bold, unexpected running-mate pick electrifies one base and unsettles the other. The whole conversation is suddenly about the bottom of the ticket.",
    trigger: { kind: "scheduled", turn: 1 },
    choices: [
      { id: "energize", text: "Let the pick energize the base and barnstorm.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05, enthusiasm: 0.03 }, { blocId: "seniors", margin: 0.03 }, { blocId: "college_white", margin: -0.02 }], momentum: 5, narrative: 1 },
        resultText: "The rallies are electric — though the press picks at the vetting." },
      { id: "steady", text: "Keep the focus up-ticket on competence.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }], momentum: 3, narrative: 4 },
        resultText: "You refuse the sideshow. Suburban voters reward the discipline." },
    ] },
  { id: "h08_crisis", title: "Wall Street in Free Fall", subject: "both", oncePerGame: true,
    prompt: "A historic financial collapse freezes credit and panics the country overnight. This is the moment the whole election turns on. How do you respond?",
    trigger: { kind: "scheduled", turn: 2 },
    choices: [
      { id: "steady_hand", text: "Project a calm, steady hand and a clear plan.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.07 }, { blocId: "seniors", margin: 0.05 }, { blocId: "college_white", margin: 0.05 }], salienceDeltas: { economy: 0.08 }, momentum: 8, narrative: 8 },
        resultText: "Composure reads as leadership. The 'who do you trust in a crisis' question breaks your way." },
      { id: "suspend", text: "Make a dramatic gesture — suspend the campaign to 'fix it.'",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03 }, { blocId: "suburban_women", margin: -0.05 }, { blocId: "college_white", margin: -0.04 }], salienceDeltas: { economy: 0.06 }, momentum: -3, narrative: -6 },
        resultText: "The stunt reads as erratic. The theatrics overshadow the substance." },
    ] },
  { id: "h08_debate1", title: "First Debate (Ole Miss)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "A debate meant to be about foreign policy is swallowed by the economy. Command of the moment matters more than any single answer.",
    trigger: { kind: "scheduled", turn: 3 },
    choices: [
      { id: "presidential", text: "Look presidential — calm, fluent, in command.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "college_white", margin: 0.05 }, { blocId: "seniors", margin: 0.03 }], momentum: 6, narrative: 7 },
        resultText: "You clear the bar and then some. The split-screen contrast lands." },
      { id: "experience", text: "Lean on experience — remind them who's ready.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.05 }, { blocId: "noncollege_white", margin: 0.03 }], momentum: 4, narrative: 3 },
        resultText: "The résumé argument holds your base; the middle is unmoved." },
    ] },
  { id: "h08_townhall", title: "The Town-Hall Debate", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "A town-hall format with real voters. Warmth and connection beat zingers. One stray, dismissive moment can define you.",
    trigger: { kind: "scheduled", turn: 5 },
    choices: [
      { id: "connect", text: "Connect — empathy, names, eye contact.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.06 }, { blocId: "youth", margin: 0.03 }], momentum: 5, narrative: 5 },
        resultText: "You work the room with ease. The likeability gap widens." },
      { id: "policy", text: "Drill into policy specifics.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.05 }, { blocId: "seniors", margin: 0.02 }], momentum: 3, narrative: 2 },
        resultText: "Substance over warmth — the wonks are pleased, the room less so." },
    ] },
  { id: "h08_closing", title: "Closing: Change vs. Experience", subject: "both", oncePerGame: true,
    prompt: "The race resolves to one question — turn the page, or steady the ship? You can only headline one closing argument.",
    trigger: { kind: "scheduled", turn: 7 },
    choices: [
      { id: "change", text: "Make it about change and the future.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.06 }, { blocId: "black", margin: 0.05 }, { blocId: "hispanic", margin: 0.04 }], momentum: 5, narrative: 4 },
        resultText: "The coalition of the ascendant turns out. Energy is on your side." },
      { id: "steady", text: "Make it about experience and steadiness.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.06 }, { blocId: "noncollege_white", margin: 0.04 }], momentum: 5, narrative: 4 },
        resultText: "The case for a known hand reassures older and rural voters." },
    ] },
];

// ── 2012 · Obama v. Romney ────────────────────────────────────────────────
export const HIST_2012: GameEvent[] = [
  { id: "h12_47", title: "A Leaked Fundraiser Tape", subject: "both", oncePerGame: true,
    prompt: "A secretly recorded line from a closed-door donor event — writing off nearly half the country — leaks and dominates the week. How do you play it?",
    trigger: { kind: "scheduled", turn: 0 },
    choices: [
      { id: "capitalize", text: "Capitalize — cut an ad and let the tape speak.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.06 }, { blocId: "noncollege_white", margin: 0.05 }, { blocId: "hispanic", margin: 0.04 }], momentum: 6, narrative: 7 },
        resultText: "The 'writes you off' framing sticks. Working and retired voters bristle at the snub." },
      { id: "weather", text: "Weather it — clarify, apologize, pivot to the economy.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03 }, { blocId: "suburban_women", margin: -0.04 }, { blocId: "seniors", margin: -0.03 }], momentum: -3, narrative: -5 },
        resultText: "The cleanup limits the damage, but the clip runs for two solid weeks." },
    ] },
  { id: "h12_debate1", title: "First Debate (Denver)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "The first debate. One of you risks coasting and looking flat; the other comes in hot and well-rehearsed. Tens of millions are watching for a moment.",
    trigger: { kind: "scheduled", turn: 2 },
    choices: [
      { id: "aggressive", text: "Come out aggressive and crisp — win the night outright.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.06 }, { blocId: "college_white", margin: 0.05 }, { blocId: "noncollege_white", margin: 0.03 }], momentum: 7, narrative: 8 },
        resultText: "You dominate the stage. The instant polls call it a rout — your way." },
      { id: "coast", text: "Play it safe and presidential — don't take the bait.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: -0.04 }, { blocId: "college_white", margin: -0.03 }], momentum: -4, narrative: -6 },
        resultText: "You look flat and disengaged. The other side gets a week of momentum." },
    ] },
  { id: "h12_vpdebate", title: "The VP Debate", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "A generational contrast on the undercard: a seasoned hand versus a young policy wonk. Whose number two helps the top of the ticket?",
    trigger: { kind: "scheduled", turn: 3 },
    choices: [
      { id: "experience", text: "Sell experience and a reassuring presence.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.05 }, { blocId: "noncollege_white", margin: 0.03 }], momentum: 4, narrative: 4 },
        resultText: "The steady hand stops the bleeding and steadies the base." },
      { id: "energy", text: "Sell youth, detail, and a sharper future.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.05 }, { blocId: "youth", margin: 0.03 }], momentum: 3, narrative: 3 },
        resultText: "The wonkish energy plays well with college and younger voters." },
    ] },
  { id: "h12_debate3", title: "Foreign-Policy Debate (Boca Raton)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "The final debate, on foreign policy. A memorable one-liner can crystallize a contrast about who belongs in the present.",
    trigger: { kind: "scheduled", turn: 5 },
    choices: [
      { id: "modern", text: "Land the modern-era zinger — make them look dated.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.05 }, { blocId: "suburban_women", margin: 0.05 }, { blocId: "youth", margin: 0.03 }], momentum: 5, narrative: 6 },
        resultText: "The line goes viral by the first commercial break. You own the clip." },
      { id: "gravitas", text: "Project sober, commander-in-chief gravitas.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.05 }, { blocId: "noncollege_white", margin: 0.03 }], momentum: 4, narrative: 4 },
        resultText: "Steady and serious — you reassure voters who want a safe pair of hands." },
    ] },
  { id: "h12_storm", title: "An October Storm", subject: "both", oncePerGame: true,
    prompt: "A monster hurricane slams the coast a week out, freezing the campaign. A rival-party governor embraces the response on camera. Govern, or campaign?",
    trigger: { kind: "scheduled", turn: 6 },
    choices: [
      { id: "govern", text: "Be the steady leader — bipartisanship over politics.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.06 }, { blocId: "seniors", margin: 0.05 }, { blocId: "college_white", margin: 0.03 }], momentum: 6, narrative: 7 },
        resultText: "The above-the-fray response and the cross-aisle praise play beautifully with the middle." },
      { id: "campaign", text: "Keep barnstorming — don't cede a single day.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04, enthusiasm: 0.02 }, { blocId: "suburban_women", margin: -0.03 }], momentum: 2, narrative: -3 },
        resultText: "You bank the rallies, but the optics of campaigning through a disaster grate." },
    ] },
  { id: "h12_closing", title: "Closing: the Ground Game", subject: "both", oncePerGame: true,
    prompt: "It's a turnout election now. The data team says it's down to who actually shows up. Where do you spend the final 72 hours?",
    trigger: { kind: "scheduled", turn: 7 },
    choices: [
      { id: "base", text: "Mobilize the base — early vote and GOTV in the cities.",
        effects: { blocDeltas: [{ blocId: "black", margin: 0.06 }, { blocId: "youth", margin: 0.05 }, { blocId: "hispanic", margin: 0.05 }], momentum: 5, narrative: 3 },
        resultText: "The vaunted turnout machine hums. Early-vote margins bank a lead." },
      { id: "persuade", text: "Chase the last persuadables in the suburbs.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.06 }, { blocId: "seniors", margin: 0.04 }], momentum: 4, narrative: 4 },
        resultText: "You win the closing argument with the deciders who break late." },
    ] },
];

// ── 2020 · Biden v. Trump (asymmetric: each ticket faces its own options) ───
// The flagship deck rebuilt: real beats, side-specific choices, real trade-offs
// (every option gains one bloc and costs another — no dominant answer).
export const HIST_2020: GameEvent[] = [
  { id: "h20_convention", title: "The Conventions Close", subject: "both", oncePerGame: true,
    prompt: "Both conventions are done — yours went half-virtual, the balloons never dropped. You've got a modest bounce and a locked base. Where do you point the campaign now?",
    trigger: { kind: "scheduled", turn: 0 },
    choices: [
      { id: "d_sunbelt", side: "dem", text: "Expand into the Sun Belt — chase Arizona, Georgia, North Carolina.",
        effects: { blocDeltas: [{ blocId: "hispanic", margin: 0.04 }, { blocId: "college_white", margin: 0.03 }, { blocId: "suburban_women", margin: 0.03 }], momentum: 3, narrative: 2 },
        resultText: "You stretch the map. The Sun Belt is suddenly live — but you're spread thin." },
      { id: "d_bluewall", side: "dem", text: "Rebuild the blue wall — turn out Black and union voters in the Midwest.",
        effects: { blocDeltas: [{ blocId: "black", margin: 0.05, enthusiasm: 0.02 }, { blocId: "noncollege_white", margin: 0.03 }], momentum: 2 },
        resultText: "You plant the flag in the Rust Belt and cede the Sun Belt for now." },
      { id: "r_base", side: "rep", text: "Rally the base — maximize rural and evangelical turnout.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05, enthusiasm: 0.02 }, { blocId: "seniors", margin: 0.03 }, { blocId: "suburban_women", margin: -0.02 }], momentum: 3 },
        resultText: "The rallies are roaring — but the ceiling with the suburbs holds." },
      { id: "r_suburbs", side: "rep", text: "Pitch the suburbs — soften the edges for college voters.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.03 }], momentum: 1, narrative: 2 },
        resultText: "You reach for the middle — and the base grumbles that you've gone soft." },
    ] },
  { id: "h20_unrest", title: "Unrest in a Battleground City", subject: "both", oncePerGame: true,
    prompt: "After another police shooting, protests and some rioting break out in a Midwestern swing state. The split-screen of marchers and burning storefronts runs on every channel. Your move.",
    trigger: { kind: "scheduled", turn: 1 },
    choices: [
      { id: "d_tightrope", side: "dem", text: "Condemn the violence and back reform — walk the tightrope.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }, { blocId: "black", margin: -0.02 }], momentum: 2, narrative: 3 },
        resultText: "The balance holds with the middle — but some of your base feels triangulated." },
      { id: "d_justice", side: "dem", text: "Stand with the protesters and make it about justice.",
        effects: { blocDeltas: [{ blocId: "black", margin: 0.06, enthusiasm: 0.03 }, { blocId: "youth", margin: 0.05 }, { blocId: "suburban_women", margin: -0.05 }, { blocId: "seniors", margin: -0.03 }], momentum: 1, narrative: -3 },
        resultText: "Your base is electrified — but the law-and-order ad writes itself for the other side." },
      { id: "r_lawandorder", side: "rep", text: "Law and order — send in the feds and run the ad.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06 }, { blocId: "seniors", margin: 0.04 }, { blocId: "suburban_women", margin: -0.05 }], salienceDeltas: { law_and_order: 0.06 }, momentum: 3, narrative: -2 },
        resultText: "The base roars approval — and suburban women recoil from the heavy hand." },
      { id: "r_calm", side: "rep", text: "Call for calm and unity — turn the temperature down.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "college_white", margin: 0.03 }, { blocId: "noncollege_white", margin: -0.03 }], momentum: 1, narrative: 3 },
        resultText: "The grace note reassures the suburbs — but your base wanted a fighter." },
    ] },
  { id: "h20_covid", title: "The Autumn COVID Wave", subject: "both", oncePerGame: true,
    prompt: "Cases surge as the weather turns — and the president himself tests positive and is hospitalized. The pandemic is the only story for a week. How do you handle it?",
    trigger: { kind: "scheduled", turn: 2 },
    choices: [
      { id: "d_science", side: "dem", text: "Lead on masks and science — model the responsible path.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.06 }, { blocId: "suburban_women", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.02 }], salienceDeltas: { covid_response: 0.06 }, momentum: 4, narrative: 5 },
        resultText: "Competence radiates. Seniors break your way — and the 'fear-monger' attack lands with rural voters." },
      { id: "d_restraint", side: "dem", text: "Show restraint and empathy — don't politicize his illness.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: 0.03 }], momentum: 2, narrative: 4 },
        resultText: "The high road plays well — but you leave the sharpest contrast on the table." },
      { id: "r_strength", side: "rep", text: "Project strength — back on the trail, downplay the risk.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06, enthusiasm: 0.03 }, { blocId: "seniors", margin: -0.04 }, { blocId: "suburban_women", margin: -0.04 }], salienceDeltas: { covid_response: -0.04 }, momentum: 3, narrative: -3 },
        resultText: "The base loves the defiance — but seniors and the suburbs are alarmed." },
      { id: "r_vaccine", side: "rep", text: "Pivot to a vaccine and a reopening message.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.04 }, { blocId: "noncollege_white", margin: 0.03 }, { blocId: "suburban_women", margin: 0.02 }], salienceDeltas: { economy: 0.04 }, momentum: 2, narrative: 1 },
        resultText: "A forward-looking pitch steadies the seniors — though it doesn't fire up the rallies." },
    ] },
  { id: "h20_scotus", title: "A Supreme Court Seat Opens", subject: "both", oncePerGame: true,
    prompt: "A liberal-lion justice dies six weeks out, and the Court is suddenly the center of the race. Small-dollar money floods both sides overnight.",
    trigger: { kind: "scheduled", turn: 3 },
    choices: [
      { id: "d_healthcare", side: "dem", text: "Make it about healthcare — the ACA is on the line.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "seniors", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }], salienceDeltas: { healthcare: 0.06 }, cash: 15_000_000, momentum: 4, narrative: 3 },
        resultText: "You sidestep the court-packing trap and fight on healthcare — your strongest ground." },
      { id: "d_pack", side: "dem", text: "Cry foul on the process and hint at expanding the Court.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.05 }, { blocId: "college_white", margin: 0.03 }, { blocId: "suburban_women", margin: -0.04 }, { blocId: "seniors", margin: -0.03 }], cash: 18_000_000, momentum: 1, narrative: -3 },
        resultText: "The base is fired up and the money pours in — but 'pack the court' spooks the middle." },
      { id: "r_ram", side: "rep", text: "Ram the nominee through — energize evangelicals.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06, enthusiasm: 0.03 }, { blocId: "seniors", margin: 0.04 }, { blocId: "suburban_women", margin: -0.04 }], salienceDeltas: { abortion: 0.05 }, cash: 18_000_000, momentum: 3, narrative: -1 },
        resultText: "The base turns out in force — and suburban women grow uneasy about the rush." },
      { id: "r_economy", side: "rep", text: "Promise a vote but keep the focus on the economy.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03 }, { blocId: "suburban_women", margin: 0.02 }, { blocId: "seniors", margin: 0.03 }], salienceDeltas: { economy: 0.04 }, cash: 12_000_000, momentum: 2, narrative: 2 },
        resultText: "Disciplined and broad — though the base wanted you to relish the brawl." },
    ] },
  { id: "h20_debate1", title: "First Debate (Cleveland)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "Ninety minutes of chaos and interruptions. The whole country is watching the most-anticipated debate of the race. How do you carry yourself on the biggest stage?",
    trigger: { kind: "scheduled", turn: 4 },
    choices: [
      { id: "calm_presidential", text: "Stay calm and presidential — talk to the camera, not your opponent.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.06 }, { blocId: "seniors", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.01 }], momentum: 7, narrative: 9 },
        resultText: "You refuse the bait. The split-screen does the work — steady and reassuring." },
      { id: "aggressive", text: "Interrupt and dominate — never yield the floor.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05, enthusiasm: 0.02 }, { blocId: "youth", margin: 0.02 }, { blocId: "suburban_women", margin: -0.05 }, { blocId: "seniors", margin: -0.03 }], momentum: 4, narrative: -6 },
        resultText: "You fire up the base — but the constant crosstalk reads as a mess at home." },
      { id: "wonk", text: "Bury them in policy detail and dare them to keep up.", requires: { trait: "policyKnowledge", min: 70 },
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.06 }, { blocId: "seniors", margin: 0.02 }], salienceDeltas: { healthcare: 0.03 }, momentum: 5, narrative: 4 },
        resultText: "Command of the substance wins the fact-checkers — a touch clinical for some." },
    ] },
  { id: "h20_vpdebate", title: "Vice-Presidential Debate (Salt Lake City)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "A calmer undercard — two running mates behind plexiglass. No knockout to be had, but a steady night reassures, and a sharp one bleeds.",
    trigger: { kind: "scheduled", turn: 5 },
    choices: [
      { id: "disciplined", text: "Stay disciplined and reassuring.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: 0.04 }], momentum: 4, narrative: 4 },
        resultText: "Your number two looks ready for the job. The grown-up tone reassures the middle." },
      { id: "offense", text: "Go on offense and draw blood.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03, enthusiasm: 0.02 }, { blocId: "suburban_women", margin: -0.03 }], momentum: 2, narrative: -2 },
        resultText: "The base enjoys the hits — but the aggression turns off the undecideds watching." },
    ] },
  { id: "h20_jobs", title: "A Surprise Jobs Report", subject: "both", oncePerGame: true,
    prompt: "The monthly jobs numbers blow past expectations — a rare bright spot in a dark year. Both campaigns scramble to spin it.",
    trigger: { kind: "scheduled", turn: 6 },
    choices: [
      { id: "r_credit", side: "rep", text: "Take the credit — the recovery is roaring back.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "seniors", margin: 0.03 }, { blocId: "suburban_women", margin: 0.02 }], salienceDeltas: { economy: 0.06 }, momentum: 4, narrative: 3 },
        resultText: "The comeback story lands — though it invites the question of how deep the hole was." },
      { id: "r_reopen", side: "rep", text: "Pair it with a full reopening message.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04 }, { blocId: "college_white", margin: 0.02 }], salienceDeltas: { economy: 0.05 }, momentum: 3, narrative: 2 },
        resultText: "You ride the optimism — and dare the other side to root against the recovery." },
      { id: "d_hole", side: "dem", text: "Remind them it's still a deep hole — millions are out of work.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04 }, { blocId: "seniors", margin: 0.03 }, { blocId: "suburban_women", margin: 0.03 }], salienceDeltas: { economy: 0.04 }, momentum: 3, narrative: 2 },
        resultText: "You contest the economy on his turf — risky, but the pain is real for many." },
      { id: "d_pivot", side: "dem", text: "Pivot back to the virus and healthcare.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: 0.04 }], salienceDeltas: { healthcare: 0.05, economy: -0.03 }, momentum: 2, narrative: 3 },
        resultText: "You change the subject to your strongest ground — and cede the good economic headline." },
    ] },
  { id: "h20_finaldebate", title: "Final Debate (Nashville)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "The last debate, with mute buttons this time. The undecideds who are left are watching for one reason to break. Make your closing case.",
    trigger: { kind: "scheduled", turn: 7 },
    choices: [
      { id: "unity", text: "Close on unity and turning the page.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }], momentum: 6, narrative: 7 },
        resultText: "You end on a high note. The closing montage practically writes itself." },
      { id: "contrast", text: "Draw a hard contrast — make it a choice, not a referendum.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "seniors", margin: 0.03 }, { blocId: "youth", margin: -0.02 }], momentum: 5, narrative: 0 },
        resultText: "You sharpen the stakes — your base is energized, a few swing voters tire of it." },
    ] },
];
