import type { GameEvent } from "@engine/types";

// Per-scenario HISTORICAL event decks + a year-agnostic debate pair for the
// "plausible / random" mode. Pure data. Each choice's bloc margins are in the
// *answering* candidate's favor (the engine flips the sign for whichever ticket
// answers). Events are mostly ASYMMETRIC: a choice tagged `side` is offered only
// to that ticket, so the two campaigns face genuinely different options for the
// same beat. Debates stay symmetric. Every choice is a trade-off — it gains one
// bloc and costs another, so there's no dominant answer.

// ── Generic debates (plausible mode, any year) ────────────────────────────
export const GENERIC_DEBATES: GameEvent[] = [
  {
    id: "gen_debate_1",
    title: "The First Presidential Debate",
    prompt: "Tens of millions tune in for the first face-off. The whole race can move in ninety minutes. How do you play the biggest stage you'll get?",
    subject: "both", isDebate: true, oncePerGame: true,
    trigger: { kind: "scheduled", turn: 4 },
    choices: [
      { id: "presidential", text: "Calm and presidential — talk past your opponent to the camera.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "seniors", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.01 }], momentum: 7, narrative: 9 },
        resultText: "You stay above the fray. The split-screen does the work — steady, reassuring." },
      { id: "aggressive", text: "Go on the attack — dominate every exchange.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05, enthusiasm: 0.02 }, { blocId: "youth", margin: 0.02 }, { blocId: "suburban_women", margin: -0.04 }], momentum: 4, narrative: -5 },
        resultText: "You fire up the base, but the crosstalk reads as a mess to voters at home." },
      { id: "wonk", text: "Win on substance — bury them in policy detail.", requires: { trait: "policyKnowledge", min: 72 },
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.06 }, { blocId: "seniors", margin: 0.02 }], salienceDeltas: { healthcare: 0.03 }, momentum: 5, narrative: 4 },
        resultText: "Command of detail wins the fact-checkers. A touch clinical for some." },
    ],
  },
  {
    id: "gen_debate_2",
    title: "The Final Debate",
    prompt: "The last debate before Election Day. The undecideds who are left are watching for one reason to break. Make your closing case.",
    subject: "both", isDebate: true, oncePerGame: true,
    trigger: { kind: "scheduled", turn: 7 },
    choices: [
      { id: "closing_unity", text: "A hopeful closing argument — turn the page.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }], momentum: 6, narrative: 7 },
        resultText: "You end on a high note. The closing montage practically writes itself." },
      { id: "closing_contrast", text: "Draw the contrast hard — make it a choice, not a referendum.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "seniors", margin: 0.03 }, { blocId: "youth", margin: -0.02 }], momentum: 5, narrative: 0 },
        resultText: "You sharpen the stakes. Your base is energized; a few swing voters tire of the negativity." },
    ],
  },
];

// ── 2024 · Harris v. Trump ────────────────────────────────────────────────
export const HIST_2024: GameEvent[] = [
  { id: "h24_switch", title: "Biden Steps Aside; Harris Takes the Ticket", subject: "both", oncePerGame: true,
    prompt: "Joe Biden's withdrawal in July handed Kamala Harris the nomination and remade the race overnight — record small-dollar money and a flood of volunteers. Democrats are energized but untested; the Trump campaign is recalibrating against an opponent it didn't expect.",
    trigger: { kind: "scheduled", turn: 0 },
    choices: [
      { id: "d_joy", side: "dem", text: "Ride the wave — a joyful, forward-looking blitz.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.06 }, { blocId: "black", margin: 0.04 }, { blocId: "suburban_women", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.02 }], cash: 9_000_000, momentum: 7, narrative: 5 },
        resultText: "The energy is real — though the vibes-over-policy critique starts to bite with blue-collar voters." },
      { id: "d_steady", side: "dem", text: "Steady the ship — reassure moderates and nervous donors.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }, { blocId: "youth", margin: -0.02 }], cash: 5_000_000, momentum: 4, narrative: 4 },
        resultText: "You lock down the center — at the cost of some of the new-found spark with the young." },
      { id: "r_attack", side: "rep", text: "Attack the switch as a backroom coup.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05, enthusiasm: 0.02 }, { blocId: "seniors", margin: 0.03 }, { blocId: "suburban_women", margin: -0.03 }], momentum: 3, narrative: -2 },
        resultText: "The base eats it up — but 'process' grievances leave the suburbs cold." },
      { id: "r_prices", side: "rep", text: "Ignore the noise — hammer prices and the border.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04 }, { blocId: "hispanic", margin: 0.04 }, { blocId: "youth", margin: -0.01 }], salienceDeltas: { economy: 0.05 }, momentum: 3, narrative: 2 },
        resultText: "Discipline on the economy steadies you — even as your rallies miss the red meat." },
    ] },
  { id: "h24_border", title: "Springfield in the Spotlight", subject: "both", oncePerGame: true,
    prompt: "A false rumor that Haitian immigrants in Springfield, Ohio are eating residents' pets rockets across social media — and gets repeated from the debate stage. Immigration is suddenly the only story.",
    trigger: { kind: "scheduled", turn: 1 },
    choices: [
      { id: "d_factcheck", side: "dem", text: "Fact-check hard and pivot to a real border plan.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "hispanic", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.03 }], salienceDeltas: { immigration: 0.03 }, momentum: 3, narrative: 4 },
        resultText: "The debunk lands with the middle — but you're playing on their turf, and the base of the other side digs in." },
      { id: "d_ignore", side: "dem", text: "Refuse to amplify it — change the subject to the economy.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03 }, { blocId: "hispanic", margin: -0.02 }], salienceDeltas: { economy: 0.04, immigration: -0.03 }, momentum: 2, narrative: 1 },
        resultText: "You starve the story of oxygen — but some Latino voters wish you'd defended them harder." },
      { id: "r_hammer", side: "rep", text: "Hammer the border as a failure of the other side.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06 }, { blocId: "seniors", margin: 0.03 }, { blocId: "hispanic", margin: -0.04 }], salienceDeltas: { immigration: 0.06 }, momentum: 4, narrative: -2 },
        resultText: "Immigration salience spikes — great for the base, a real turnoff for Latino voters." },
      { id: "r_temper", side: "rep", text: "Dial back the rumor, keep the focus on prices.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "hispanic", margin: 0.02 }, { blocId: "noncollege_white", margin: -0.02 }], salienceDeltas: { economy: 0.04 }, momentum: 1, narrative: 2 },
        resultText: "The restraint keeps the suburbs in reach — and your base wonders why you went soft." },
    ] },
  { id: "h24_debate", title: "The Philadelphia Debate (ABC)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "The first and only Harris–Trump debate, prime-time on ABC out of Philadelphia. The whole campaign has waited for this matchup. Set the terms.",
    trigger: { kind: "scheduled", turn: 2 },
    choices: [
      { id: "bait", text: "Bait the temper — get under your opponent's skin on crowd sizes and grievance.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.06 }, { blocId: "college_white", margin: 0.05 }, { blocId: "noncollege_white", margin: -0.02 }], momentum: 6, narrative: 8 },
        resultText: "The bait works. Your opponent spends ninety minutes defending the indefensible." },
      { id: "economy", text: "Stay laser-focused on prices and the cost of living.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "hispanic", margin: 0.03 }, { blocId: "youth", margin: -0.01 }], salienceDeltas: { economy: 0.05 }, momentum: 4, narrative: 2 },
        resultText: "Disciplined and on-message — you win the voters who only care about their wallet." },
    ] },
  { id: "h24_security", title: "An Assassination Attempt on Trump", subject: "rep", oncePerGame: true,
    prompt: "A gunman opens fire at a Trump rally. He survives — bloodied, fist raised — and the country freezes for forty-eight hours. The tone of the race is suddenly up for grabs.",
    trigger: { kind: "scheduled", turn: 3 },
    choices: [
      { id: "r_defiance", side: "rep", text: "Project defiance and resolve — fist in the air, never back down.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06, enthusiasm: 0.03 }, { blocId: "suburban_women", margin: -0.02 }], momentum: 5, narrative: 1 },
        resultText: "The image of defiance becomes an instant rallying icon for your base." },
      { id: "r_unity", side: "rep", text: "Strike a unifying note — lower the temperature.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "seniors", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.02 }], momentum: 3, narrative: 5 },
        resultText: "A rare moment of grace broadens your appeal — though the base wanted the fist." },
      { id: "d_calm", side: "dem", text: "Condemn political violence and call for calm.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: 0.04 }], momentum: 3, narrative: 5 },
        resultText: "The statesmanlike response plays well with a jittery middle." },
      { id: "d_focus", side: "dem", text: "Pause briefly, then get back to your own message.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.03 }, { blocId: "black", margin: 0.03 }, { blocId: "suburban_women", margin: -0.02 }], momentum: 2, narrative: 0 },
        resultText: "You keep your coalition focused — but the optics of campaigning through it draw some criticism." },
    ] },
  { id: "h24_closing", title: "The Closing Argument: Prices vs. Rights", subject: "both", oncePerGame: true,
    prompt: "The race narrows to two questions: can you afford your life, and who decides your rights after the fall of Roe? You can only headline one.",
    trigger: { kind: "scheduled", turn: 5 },
    choices: [
      { id: "d_rights", side: "dem", text: "Make it about rights and democracy.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.06 }, { blocId: "youth", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.02 }], salienceDeltas: { abortion: 0.05 }, momentum: 5, narrative: 4 },
        resultText: "You consolidate the coalition that turns out on rights — but cede the economy frame." },
      { id: "d_prices", side: "dem", text: "Make it about prices and the economy.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06 }, { blocId: "hispanic", margin: 0.04 }, { blocId: "youth", margin: -0.02 }], salienceDeltas: { economy: 0.06 }, momentum: 5, narrative: 3 },
        resultText: "Kitchen-table economics wins the persuadables who decide late — at the cost of base intensity." },
      { id: "r_prices", side: "rep", text: "Close on prices and the border.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06 }, { blocId: "hispanic", margin: 0.04 }, { blocId: "suburban_women", margin: -0.01 }], salienceDeltas: { economy: 0.05 }, momentum: 5, narrative: 3 },
        resultText: "You ride the cost-of-living wave with the working class straight to the finish." },
      { id: "r_strength", side: "rep", text: "Close on strength and law and order.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05, enthusiasm: 0.02 }, { blocId: "seniors", margin: 0.04 }, { blocId: "suburban_women", margin: -0.04 }], salienceDeltas: { law_and_order: 0.05 }, momentum: 4, narrative: -1 },
        resultText: "The strongman close maxes out the base — and the suburbs flinch one last time." },
    ] },
];

// ── 2020 · Biden v. Trump (asymmetric flagship deck) ────────────────────────
export const HIST_2020: GameEvent[] = [
  { id: "h20_convention", title: "Two Conventions, One Pandemic", subject: "both", oncePerGame: true,
    prompt: "The conventions are done — Biden's beamed in from a near-empty hall in Wilmington, Trump's staged on the White House South Lawn. Modest bounces, locked-in bases. Where do you point the campaign now?",
    trigger: { kind: "scheduled", turn: 0 },
    choices: [
      { id: "d_sunbelt", side: "dem", text: "Expand into the Sun Belt — chase Arizona, Georgia, North Carolina.",
        effects: { blocDeltas: [{ blocId: "hispanic", margin: 0.04 }, { blocId: "college_white", margin: 0.03 }, { blocId: "suburban_women", margin: 0.03 }], momentum: 3, narrative: 2 },
        resultText: "You stretch the map. The Sun Belt is suddenly live — but you're spread thin." },
      { id: "d_bluewall", side: "dem", text: "Rebuild the blue wall — turn out Black and union voters in the Midwest.",
        effects: { blocDeltas: [{ blocId: "black", margin: 0.05, enthusiasm: 0.02 }, { blocId: "noncollege_white", margin: 0.03 }], momentum: 2 },
        resultText: "You plant the flag in the Rust Belt and cede the Sun Belt for now." },
      { id: "r_base", side: "rep", text: "Rally the base — maximize rural and evangelical turnout.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05, enthusiasm: 0.02 }, { blocId: "seniors", margin: 0.03 }, { blocId: "suburban_women", margin: -0.02 }], momentum: 3 },
        resultText: "The rallies are roaring — but the ceiling with the suburbs holds." },
      { id: "r_suburbs", side: "rep", text: "Pitch the suburbs — soften the edges for college voters.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.03 }], momentum: 1, narrative: 2 },
        resultText: "You reach for the middle — and the base grumbles that you've gone soft." },
    ] },
  { id: "h20_unrest", title: "Unrest in Kenosha", subject: "both", oncePerGame: true,
    prompt: "After the police shooting of Jacob Blake, protests and some rioting break out in Kenosha, Wisconsin. The split-screen of marchers and burning storefronts runs on every channel in a state you have to win. Your move.",
    trigger: { kind: "scheduled", turn: 1 },
    choices: [
      { id: "d_tightrope", side: "dem", text: "Condemn the violence and back reform — walk the tightrope.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }, { blocId: "black", margin: -0.02 }], momentum: 2, narrative: 3 },
        resultText: "The balance holds with the middle — but some of your base feels triangulated." },
      { id: "d_justice", side: "dem", text: "Stand with the protesters and make it about justice.",
        effects: { blocDeltas: [{ blocId: "black", margin: 0.06, enthusiasm: 0.03 }, { blocId: "youth", margin: 0.05 }, { blocId: "suburban_women", margin: -0.05 }, { blocId: "seniors", margin: -0.03 }], momentum: 1, narrative: -3 },
        resultText: "Your base is electrified — but the law-and-order ad writes itself for the other side." },
      { id: "r_lawandorder", side: "rep", text: "Law and order — send in the feds and run the ad.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06 }, { blocId: "seniors", margin: 0.04 }, { blocId: "suburban_women", margin: -0.05 }], salienceDeltas: { law_and_order: 0.06 }, momentum: 3, narrative: -2 },
        resultText: "The base roars approval — and suburban women recoil from the heavy hand." },
      { id: "r_calm", side: "rep", text: "Call for calm and unity — turn the temperature down.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "college_white", margin: 0.03 }, { blocId: "noncollege_white", margin: -0.03 }], momentum: 1, narrative: 3 },
        resultText: "The grace note reassures the suburbs — but your base wanted a fighter." },
    ] },
  { id: "h20_covid", title: "Trump Hospitalized with COVID", subject: "both", oncePerGame: true,
    prompt: "Cases surge as the weather turns — and Trump himself tests positive and is flown to Walter Reed. The pandemic is the only story for a week. How do you handle it?",
    trigger: { kind: "scheduled", turn: 2 },
    choices: [
      { id: "d_science", side: "dem", text: "Lead on masks and science — model the responsible path.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.06 }, { blocId: "suburban_women", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.02 }], salienceDeltas: { covid_response: 0.06 }, momentum: 4, narrative: 5 },
        resultText: "Competence radiates. Seniors break your way — and the 'fear-monger' attack lands with rural voters." },
      { id: "d_restraint", side: "dem", text: "Show restraint and empathy — don't politicize his illness.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: 0.03 }], momentum: 2, narrative: 4 },
        resultText: "The high road plays well — but you leave the sharpest contrast on the table." },
      { id: "r_strength", side: "rep", text: "Project strength — back on the trail, downplay the risk.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06, enthusiasm: 0.03 }, { blocId: "seniors", margin: -0.04 }, { blocId: "suburban_women", margin: -0.04 }], salienceDeltas: { covid_response: -0.04 }, momentum: 3, narrative: -3 },
        resultText: "The base loves the defiance — but seniors and the suburbs are alarmed." },
      { id: "r_vaccine", side: "rep", text: "Pivot to a vaccine and a reopening message.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.04 }, { blocId: "noncollege_white", margin: 0.03 }, { blocId: "suburban_women", margin: 0.02 }], salienceDeltas: { economy: 0.04 }, momentum: 2, narrative: 1 },
        resultText: "A forward-looking pitch steadies the seniors — though it doesn't fire up the rallies." },
    ] },
  { id: "h20_scotus", title: "Ruth Bader Ginsburg Dies", subject: "both", oncePerGame: true,
    prompt: "Justice Ruth Bader Ginsburg dies six weeks out, and the Supreme Court is suddenly the center of the race — with a fight over filling the seat before Election Day. Small-dollar money floods both sides overnight.",
    trigger: { kind: "scheduled", turn: 3 },
    choices: [
      { id: "d_healthcare", side: "dem", text: "Make it about healthcare — the ACA is on the line.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "seniors", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }], salienceDeltas: { healthcare: 0.06 }, cash: 15_000_000, momentum: 4, narrative: 3 },
        resultText: "You sidestep the court-packing trap and fight on healthcare — your strongest ground." },
      { id: "d_pack", side: "dem", text: "Cry foul on the process and hint at expanding the Court.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.05 }, { blocId: "college_white", margin: 0.03 }, { blocId: "suburban_women", margin: -0.04 }, { blocId: "seniors", margin: -0.03 }], cash: 18_000_000, momentum: 1, narrative: -3 },
        resultText: "The base is fired up and the money pours in — but 'pack the court' spooks the middle." },
      { id: "r_ram", side: "rep", text: "Ram the nominee through — energize evangelicals.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06, enthusiasm: 0.03 }, { blocId: "seniors", margin: 0.04 }, { blocId: "suburban_women", margin: -0.04 }], salienceDeltas: { abortion: 0.05 }, cash: 18_000_000, momentum: 3, narrative: -1 },
        resultText: "The base turns out in force — and suburban women grow uneasy about the rush." },
      { id: "r_economy", side: "rep", text: "Promise a vote but keep the focus on the economy.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03 }, { blocId: "suburban_women", margin: 0.02 }, { blocId: "seniors", margin: 0.03 }], salienceDeltas: { economy: 0.04 }, cash: 12_000_000, momentum: 2, narrative: 2 },
        resultText: "Disciplined and broad — though the base wanted you to relish the brawl." },
    ] },
  { id: "h20_debate1", title: "First Debate (Cleveland)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "Ninety minutes of chaos and interruptions in Cleveland — \"Will you shut up, man?\" Biden and Trump talk over each other for the most-anticipated debate of the race. How do you carry yourself on the biggest stage?",
    trigger: { kind: "scheduled", turn: 4 },
    choices: [
      { id: "calm_presidential", text: "Stay calm and presidential — talk to the camera, not your opponent.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.06 }, { blocId: "seniors", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.01 }], momentum: 7, narrative: 9 },
        resultText: "You refuse the bait. The split-screen does the work — steady and reassuring." },
      { id: "aggressive", text: "Interrupt and dominate — never yield the floor.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05, enthusiasm: 0.02 }, { blocId: "youth", margin: 0.02 }, { blocId: "suburban_women", margin: -0.05 }, { blocId: "seniors", margin: -0.03 }], momentum: 4, narrative: -6 },
        resultText: "You fire up the base — but the constant crosstalk reads as a mess at home." },
      { id: "wonk", text: "Bury them in policy detail and dare them to keep up.", requires: { trait: "policyKnowledge", min: 70 },
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.06 }, { blocId: "seniors", margin: 0.02 }], salienceDeltas: { healthcare: 0.03 }, momentum: 5, narrative: 4 },
        resultText: "Command of the substance wins the fact-checkers — a touch clinical for some." },
    ] },
  { id: "h20_vpdebate", title: "Vice-Presidential Debate (Salt Lake City)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "A calmer undercard in Salt Lake City — two running mates behind plexiglass, and a fly that lands on one of them long enough to steal the night. No knockout to be had, but a steady showing reassures, and a sharp one bleeds.",
    trigger: { kind: "scheduled", turn: 5 },
    choices: [
      { id: "disciplined", text: "Stay disciplined and reassuring.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: 0.04 }], momentum: 4, narrative: 4 },
        resultText: "Your number two looks ready for the job. The grown-up tone reassures the middle." },
      { id: "offense", text: "Go on offense and draw blood.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03, enthusiasm: 0.02 }, { blocId: "suburban_women", margin: -0.03 }], momentum: 2, narrative: -2 },
        resultText: "The base enjoys the hits — but the aggression turns off the undecideds watching." },
    ] },
  { id: "h20_jobs", title: "A Surprise Jobs Report", subject: "both", oncePerGame: true,
    prompt: "The monthly jobs numbers blow past expectations — a rare bright spot in a dark year. Both campaigns scramble to spin it.",
    trigger: { kind: "scheduled", turn: 6 },
    choices: [
      { id: "r_credit", side: "rep", text: "Take the credit — the recovery is roaring back.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "seniors", margin: 0.03 }, { blocId: "suburban_women", margin: 0.02 }], salienceDeltas: { economy: 0.06 }, momentum: 4, narrative: 3 },
        resultText: "The comeback story lands — though it invites the question of how deep the hole was." },
      { id: "r_reopen", side: "rep", text: "Pair it with a full reopening message.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04 }, { blocId: "college_white", margin: 0.02 }], salienceDeltas: { economy: 0.05 }, momentum: 3, narrative: 2 },
        resultText: "You ride the optimism — and dare the other side to root against the recovery." },
      { id: "d_hole", side: "dem", text: "Remind them it's still a deep hole — millions are out of work.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04 }, { blocId: "seniors", margin: 0.03 }, { blocId: "suburban_women", margin: 0.03 }], salienceDeltas: { economy: 0.04 }, momentum: 3, narrative: 2 },
        resultText: "You contest the economy on his turf — risky, but the pain is real for many." },
      { id: "d_pivot", side: "dem", text: "Pivot back to the virus and healthcare.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: 0.04 }], salienceDeltas: { healthcare: 0.05, economy: -0.03 }, momentum: 2, narrative: 3 },
        resultText: "You change the subject to your strongest ground — and cede the good economic headline." },
    ] },
  { id: "h20_finaldebate", title: "Final Debate (Nashville)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "The last Biden–Trump debate in Nashville, with mute buttons this time to keep it civil. The undecideds who are left are watching for one reason to break. Make your closing case.",
    trigger: { kind: "scheduled", turn: 7 },
    choices: [
      { id: "unity", text: "Close on unity and turning the page.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }], momentum: 6, narrative: 7 },
        resultText: "You end on a high note. The closing montage practically writes itself." },
      { id: "contrast", text: "Draw a hard contrast — make it a choice, not a referendum.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "seniors", margin: 0.03 }, { blocId: "youth", margin: -0.02 }], momentum: 5, narrative: 0 },
        resultText: "You sharpen the stakes — your base is energized, a few swing voters tire of it." },
    ] },
];

// ── 2016 · Clinton v. Trump ───────────────────────────────────────────────
export const HIST_2016: GameEvent[] = [
  { id: "h16_deplorables", title: "The 'Basket of Deplorables'", subject: "dem", oncePerGame: true,
    prompt: "Hillary Clinton's line from a closed-door fundraiser — half of Trump's supporters dropped into a \"basket of deplorables\" — leaks and is everywhere by morning.",
    trigger: { kind: "scheduled", turn: 0 },
    choices: [
      { id: "d_walk", side: "dem", text: "Walk it back — say you regret the generalization.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: 0.03 }, { blocId: "youth", margin: -0.02 }], momentum: 1, narrative: 3 },
        resultText: "The cleanup holds with the middle — though the base wishes you'd stood your ground." },
      { id: "d_double", side: "dem", text: "Stand by the sentiment — call out the bigotry by name.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.04 }, { blocId: "youth", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.06 }], momentum: 2, narrative: -3 },
        resultText: "The base cheers — but the clip becomes the other side's favorite recruiting tool." },
      { id: "r_grievance", side: "rep", text: "Make it about the insult — 'they look down on you.'",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06, enthusiasm: 0.03 }, { blocId: "seniors", margin: 0.03 }, { blocId: "college_white", margin: -0.01 }], momentum: 4, narrative: 1 },
        resultText: "The grievance lands hard with working-class voters who feel sneered at." },
      { id: "r_presidential", side: "rep", text: "Stay above it and look presidential for once.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "college_white", margin: 0.03 }, { blocId: "noncollege_white", margin: -0.02 }], momentum: 1, narrative: 3 },
        resultText: "A rare disciplined day reassures wary suburbanites — and bores the base." },
    ] },
  { id: "h16_health", title: "A Stumble at a 9/11 Memorial", subject: "dem", oncePerGame: true,
    prompt: "Hillary Clinton buckles and is helped into a van leaving the 9/11 memorial, caught on a bystander's phone. A pneumonia diagnosis the campaign had sat on sets off a stamina frenzy.",
    trigger: { kind: "scheduled", turn: 1 },
    choices: [
      { id: "d_records", side: "dem", text: "Release detailed medical records and get back out fast.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.05 }, { blocId: "suburban_women", margin: 0.03 }], momentum: 4, narrative: 5 },
        resultText: "Transparency defuses it. A brisk rally swing puts the stamina story to bed." },
      { id: "d_powerthrough", side: "dem", text: "Power through — pack the schedule, say little.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.02 }, { blocId: "seniors", margin: -0.04 }], momentum: 2, narrative: -3 },
        resultText: "You project toughness, but the silence lets the speculation run another week." },
      { id: "r_amplify", side: "rep", text: "Amplify the stamina question — 'is she up to it?'",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04 }, { blocId: "seniors", margin: 0.04 }, { blocId: "suburban_women", margin: -0.03 }], momentum: 3, narrative: -2 },
        resultText: "The doubts spread — though piling on a sick opponent costs you with women." },
      { id: "r_restraint", side: "rep", text: "Show uncharacteristic restraint and wish her well.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: 0.03 }], momentum: 1, narrative: 3 },
        resultText: "Magnanimity surprises the press and softens your edges — for a day." },
    ] },
  { id: "h16_debate1", title: "First Debate (Hofstra)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "Clinton vs. Trump at Hofstra — the most-watched debate in history. One of you is over-prepared, one is winging it. Ninety minutes to define the race.",
    trigger: { kind: "scheduled", turn: 2 },
    choices: [
      { id: "bait", text: "Set traps — bait your opponent into an unforced error.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.05 }, { blocId: "suburban_women", margin: 0.05 }, { blocId: "noncollege_white", margin: -0.02 }], momentum: 6, narrative: 8 },
        resultText: "The traps spring. The post-debate clips run against your opponent for days." },
      { id: "punch", text: "Throw haymakers — never concede a point.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05, enthusiasm: 0.02 }, { blocId: "suburban_women", margin: -0.04 }], momentum: 3, narrative: -4 },
        resultText: "The base is thrilled; suburban viewers are exhausted." },
    ] },
  { id: "h16_tape", title: "An 'Access Hollywood' Bombshell", subject: "rep", oncePerGame: true,
    prompt: "A decade-old hot-mic recording of the Republican nominee surfaces a month out, and it is ugly. Down-ballot allies are running for the exits. This is the hinge of the campaign.",
    trigger: { kind: "scheduled", turn: 4 },
    choices: [
      { id: "r_apologize", side: "rep", text: "Apologize, contain the damage, and counterpunch.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03, enthusiasm: 0.02 }, { blocId: "suburban_women", margin: -0.06 }, { blocId: "seniors", margin: -0.03 }], momentum: -4, narrative: -6 },
        resultText: "The base sticks, but the bleeding with women and seniors doesn't fully stop." },
      { id: "r_dismiss", side: "rep", text: "Dismiss it as 'locker-room talk' and change the subject.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.02 }, { blocId: "suburban_women", margin: -0.08 }], momentum: -5, narrative: -8 },
        resultText: "The framing collapses on contact. The story runs for two solid weeks." },
      { id: "d_capitalize", side: "dem", text: "Capitalize — cut a contrast ad tonight and let it breathe.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.07 }, { blocId: "college_white", margin: 0.05 }, { blocId: "noncollege_white", margin: -0.01 }], momentum: 8, narrative: 9 },
        resultText: "You let the tape do the talking. Suburban women break hard your way." },
      { id: "d_aboveit", side: "dem", text: "Stay above it — keep your own closing message.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.03 }, { blocId: "seniors", margin: 0.02 }], momentum: 3, narrative: 4 },
        resultText: "Discipline reads as classy — but you leave a free shot on the table." },
    ] },
  { id: "h16_debate3", title: "Final Debate (Las Vegas)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "Last debate, in Las Vegas. Trump won't say he'll accept the result — \"I'll keep you in suspense\" — and the night turns on whether you'll respect the voters. Your answer will be the headline.",
    trigger: { kind: "scheduled", turn: 6 },
    choices: [
      { id: "respect", text: "Pledge to respect the result, whatever it is.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "seniors", margin: 0.04 }], momentum: 5, narrative: 7 },
        resultText: "Reassuring to the middle. The clip ages well." },
      { id: "suspense", text: "Keep them in suspense — 'I'll let you know.'",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04, enthusiasm: 0.02 }, { blocId: "college_white", margin: -0.05 }], momentum: 2, narrative: -6 },
        resultText: "The base eats it up; the press calls it unprecedented for a week." },
    ] },
  { id: "h16_letter", title: "The Comey Letter", subject: "dem", oncePerGame: true,
    prompt: "Eleven days out, FBI Director James Comey writes Congress that the bureau is reviewing newly found emails — reopening the closed investigation into Clinton's server. No new facts yet, just a cloud, at the worst possible moment.",
    trigger: { kind: "scheduled", turn: 7 },
    choices: [
      { id: "d_fight", side: "dem", text: "Fight the process — demand they release everything now.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.04 }, { blocId: "suburban_women", margin: 0.02 }], momentum: 1, narrative: 2 },
        resultText: "You blunt it, but the story still dominates a precious final week." },
      { id: "d_ignore", side: "dem", text: "Ignore it — relentlessly stay on your own message.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.03 }, { blocId: "noncollege_white", margin: -0.02 }, { blocId: "seniors", margin: -0.02 }], momentum: 0, narrative: 1 },
        resultText: "Discipline keeps you on offense — but the cloud lingers in the background." },
      { id: "r_amplify", side: "rep", text: "Amplify it — make it the closing argument.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "seniors", margin: 0.04 }, { blocId: "college_white", margin: -0.01 }], momentum: 6, narrative: 4 },
        resultText: "The cloud does your closing work for you. Undecideds wobble your way." },
      { id: "r_discipline", side: "rep", text: "Resist the urge — keep hammering trade and jobs.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04 }, { blocId: "suburban_women", margin: 0.01 }], salienceDeltas: { economy: 0.04 }, momentum: 3, narrative: 2 },
        resultText: "Staying on the economy reassures the suburbs — and lets a gift cool off." },
    ] },
];

// ── 2012 · Obama v. Romney ────────────────────────────────────────────────
export const HIST_2012: GameEvent[] = [
  { id: "h12_47", title: "The 47 Percent Tape", subject: "rep", oncePerGame: true,
    prompt: "A secretly recorded clip from a Romney donor dinner — writing off \"47 percent\" of the country as freeloaders who'll never take responsibility — leaks and dominates the week.",
    trigger: { kind: "scheduled", turn: 0 },
    choices: [
      { id: "r_clarify", side: "rep", text: "Clarify and apologize — say it came out wrong.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03 }, { blocId: "suburban_women", margin: -0.04 }, { blocId: "seniors", margin: -0.03 }], momentum: -3, narrative: -4 },
        resultText: "The cleanup limits the damage — but the clip runs for two solid weeks." },
      { id: "r_defend", side: "rep", text: "Defend the makers-vs-takers point on principle.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04, enthusiasm: 0.02 }, { blocId: "seniors", margin: -0.05 }, { blocId: "hispanic", margin: -0.03 }], momentum: -2, narrative: -5 },
        resultText: "The donor class nods — and seniors who rely on a check are furious." },
      { id: "d_capitalize", side: "dem", text: "Capitalize — cut an ad and let the tape speak.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.06 }, { blocId: "noncollege_white", margin: 0.05 }, { blocId: "hispanic", margin: 0.04 }], momentum: 6, narrative: 7 },
        resultText: "The 'writes you off' framing sticks. Working and retired voters bristle at the snub." },
      { id: "d_aboveit", side: "dem", text: "Let it speak for itself — stay on your own jobs message.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03 }, { blocId: "college_white", margin: 0.02 }], salienceDeltas: { economy: 0.03 }, momentum: 3, narrative: 3 },
        resultText: "You keep it clean — and trust the tape to do its own damage." },
    ] },
  { id: "h12_debate1", title: "First Debate (Denver)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "The first debate, in Denver. Obama risks coasting and looking flat; Romney comes in hot and well-rehearsed. Tens of millions are watching for a moment.",
    trigger: { kind: "scheduled", turn: 2 },
    choices: [
      { id: "aggressive", text: "Come out aggressive and crisp — win the night outright.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.06 }, { blocId: "college_white", margin: 0.05 }, { blocId: "noncollege_white", margin: 0.03 }], momentum: 7, narrative: 8 },
        resultText: "You dominate the stage. The instant polls call it a rout — your way." },
      { id: "coast", text: "Play it safe and presidential — don't take the bait.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: -0.04 }, { blocId: "college_white", margin: -0.03 }], momentum: -4, narrative: -6 },
        resultText: "You look flat and disengaged. The other side gets a week of momentum." },
    ] },
  { id: "h12_vpdebate", title: "The VP Debate", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "A generational contrast on the undercard: a seasoned hand versus a young policy wonk. Whose number two helps the top of the ticket?",
    trigger: { kind: "scheduled", turn: 3 },
    choices: [
      { id: "experience", text: "Sell experience and a reassuring presence.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.05 }, { blocId: "noncollege_white", margin: 0.03 }], momentum: 4, narrative: 4 },
        resultText: "The steady hand stops the bleeding and steadies the base." },
      { id: "energy", text: "Sell youth, detail, and a sharper future.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.05 }, { blocId: "youth", margin: 0.03 }], momentum: 3, narrative: 3 },
        resultText: "The wonkish energy plays well with college and younger voters." },
    ] },
  { id: "h12_debate3", title: "Foreign-Policy Debate (Boca Raton)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "The final debate, in Boca Raton, on foreign policy. \"The 1980s are calling to ask for their foreign policy back\" — \"horses and bayonets\" — a one-liner can crystallize who belongs in the present.",
    trigger: { kind: "scheduled", turn: 5 },
    choices: [
      { id: "modern", text: "Land the modern-era zinger — make them look dated.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.05 }, { blocId: "suburban_women", margin: 0.05 }, { blocId: "youth", margin: 0.03 }], momentum: 5, narrative: 6 },
        resultText: "The line goes viral by the first commercial break. You own the clip." },
      { id: "gravitas", text: "Project sober, commander-in-chief gravitas.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.05 }, { blocId: "noncollege_white", margin: 0.03 }], momentum: 4, narrative: 4 },
        resultText: "Steady and serious — you reassure voters who want a safe pair of hands." },
    ] },
  { id: "h12_storm", title: "Hurricane Sandy", subject: "both", oncePerGame: true,
    prompt: "Superstorm Sandy slams the East Coast a week out, freezing the campaign. New Jersey's Republican governor, Chris Christie, praises Obama's federal response on camera — a bipartisan embrace days before the vote.",
    trigger: { kind: "scheduled", turn: 6 },
    choices: [
      { id: "d_govern", side: "dem", text: "Be the steady leader — bipartisanship over politics.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.06 }, { blocId: "seniors", margin: 0.05 }, { blocId: "college_white", margin: 0.03 }], momentum: 6, narrative: 7 },
        resultText: "The above-the-fray response and the cross-aisle praise play beautifully with the middle." },
      { id: "d_campaign", side: "dem", text: "Keep barnstorming — don't cede a single day.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04, enthusiasm: 0.02 }, { blocId: "suburban_women", margin: -0.03 }], momentum: 2, narrative: -3 },
        resultText: "You bank the rallies, but campaigning through a disaster grates." },
      { id: "r_restraint", side: "rep", text: "Pause respectfully and avoid looking partisan.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: 0.03 }, { blocId: "noncollege_white", margin: -0.02 }], momentum: 1, narrative: 3 },
        resultText: "Restraint avoids an own-goal — but you lose a crucial week of momentum." },
      { id: "r_push", side: "rep", text: "Press the closing economic argument anyway.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04 }, { blocId: "college_white", margin: 0.02 }], salienceDeltas: { economy: 0.04 }, momentum: 3, narrative: -2 },
        resultText: "You keep the economy front and center — and risk looking tone-deaf." },
    ] },
  { id: "h12_closing", title: "Closing: the Ground Game", subject: "both", oncePerGame: true,
    prompt: "It's a turnout election now. The data teams say it's down to who actually shows up. Where do you spend the final 72 hours?",
    trigger: { kind: "scheduled", turn: 7 },
    choices: [
      { id: "d_base", side: "dem", text: "Mobilize the base — early vote and GOTV in the cities.",
        effects: { blocDeltas: [{ blocId: "black", margin: 0.06 }, { blocId: "youth", margin: 0.05 }, { blocId: "hispanic", margin: 0.05 }, { blocId: "noncollege_white", margin: -0.01 }], momentum: 5, narrative: 3 },
        resultText: "The vaunted turnout machine hums. Early-vote margins bank a lead." },
      { id: "d_persuade", side: "dem", text: "Chase the last persuadables in the suburbs.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "seniors", margin: 0.04 }, { blocId: "youth", margin: -0.02 }], momentum: 4, narrative: 4 },
        resultText: "You win the closing argument with the deciders who break late." },
      { id: "r_enthusiasm", side: "rep", text: "Bet on enthusiasm — big rallies to drive base turnout.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06, enthusiasm: 0.02 }, { blocId: "seniors", margin: 0.03 }], momentum: 5, narrative: 2 },
        resultText: "The crowds are enormous — you're counting on intensity to beat their machine." },
      { id: "r_late", side: "rep", text: "Make a late play for the suburbs and independents.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.02 }], momentum: 4, narrative: 3 },
        resultText: "You broaden the map late — though the base wishes you'd just fed the rallies." },
    ] },
];

// ── 2008 · Obama v. McCain ────────────────────────────────────────────────
export const HIST_2008: GameEvent[] = [
  { id: "h08_palin", title: "A Surprise on the Republican Ticket", subject: "rep", oncePerGame: true,
    prompt: "A bold, unexpected running-mate pick electrifies the Republican base and unsettles everyone else. The whole conversation is suddenly about the bottom of the ticket.",
    trigger: { kind: "scheduled", turn: 0 },
    choices: [
      { id: "r_energize", side: "rep", text: "Let the pick energize the base and barnstorm.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05, enthusiasm: 0.03 }, { blocId: "seniors", margin: 0.03 }, { blocId: "college_white", margin: -0.03 }], momentum: 5, narrative: 1 },
        resultText: "The rallies are electric — though the press picks at the vetting." },
      { id: "r_steady", side: "rep", text: "Keep the focus up-ticket on experience.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "college_white", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.02 }], momentum: 3, narrative: 4 },
        resultText: "You refuse the sideshow — and the base loses some of its new spark." },
      { id: "d_engage", side: "dem", text: "Engage the pick directly and question the readiness.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.04 }, { blocId: "suburban_women", margin: 0.03 }, { blocId: "noncollege_white", margin: -0.03 }], momentum: 2, narrative: -1 },
        resultText: "You raise real doubts — but risk elevating a star and looking dismissive." },
      { id: "d_ignore", side: "dem", text: "Ignore the running mate — stay on the economy.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04 }, { blocId: "seniors", margin: 0.02 }], salienceDeltas: { economy: 0.04 }, momentum: 3, narrative: 3 },
        resultText: "You keep the race about kitchen tables — and deny the other side the spotlight." },
    ] },
  { id: "h08_crisis", title: "Lehman Falls; Wall Street in Free Fall", subject: "both", oncePerGame: true,
    prompt: "Lehman Brothers collapses, credit freezes, and the country panics overnight as Washington scrambles for a bailout. This is the moment the whole election turns on. How do you respond?",
    trigger: { kind: "scheduled", turn: 2 },
    choices: [
      { id: "d_steady", side: "dem", text: "Project a calm, steady hand and a clear plan.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.07 }, { blocId: "seniors", margin: 0.05 }, { blocId: "college_white", margin: 0.05 }], salienceDeltas: { economy: 0.08 }, momentum: 8, narrative: 8 },
        resultText: "Composure reads as leadership. The 'who do you trust in a crisis' question breaks your way." },
      { id: "d_populist", side: "dem", text: "Channel the anger — blame deregulation and Wall Street.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05, enthusiasm: 0.02 }, { blocId: "youth", margin: 0.04 }, { blocId: "seniors", margin: -0.02 }], salienceDeltas: { economy: 0.07 }, momentum: 5, narrative: 3 },
        resultText: "The populism fires up the base — though it spooks some cautious retirees." },
      { id: "r_suspend", side: "rep", text: "Make a dramatic gesture — 'suspend' the campaign to fix it.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03 }, { blocId: "suburban_women", margin: -0.05 }, { blocId: "college_white", margin: -0.04 }], salienceDeltas: { economy: 0.06 }, momentum: -3, narrative: -6 },
        resultText: "The stunt reads as erratic. The theatrics overshadow the substance." },
      { id: "r_steady", side: "rep", text: "Stress experience and a steady hand through the storm.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.05 }, { blocId: "noncollege_white", margin: 0.03 }, { blocId: "youth", margin: -0.02 }], salienceDeltas: { economy: 0.05 }, momentum: 3, narrative: 2 },
        resultText: "The 'tested' argument holds the base — but it's the other side's issue now." },
    ] },
  { id: "h08_debate1", title: "First Debate (Ole Miss)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "Obama and McCain at Ole Miss — a debate meant to be about foreign policy, swallowed by the economic crisis. Command of the moment matters more than any single answer.",
    trigger: { kind: "scheduled", turn: 3 },
    choices: [
      { id: "presidential", text: "Look presidential — calm, fluent, in command.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "college_white", margin: 0.05 }, { blocId: "seniors", margin: 0.03 }], momentum: 6, narrative: 7 },
        resultText: "You clear the bar and then some. The split-screen contrast lands." },
      { id: "experience", text: "Lean on experience — remind them who's ready.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.05 }, { blocId: "noncollege_white", margin: 0.03 }], momentum: 4, narrative: 3 },
        resultText: "The résumé argument holds your base; the middle is unmoved." },
    ] },
  { id: "h08_townhall", title: "The Town-Hall Debate", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "Obama and McCain in a town-hall format with real voters — the night of \"that one.\" Warmth and connection beat zingers, and one stray, dismissive moment can define you.",
    trigger: { kind: "scheduled", turn: 5 },
    choices: [
      { id: "connect", text: "Connect — empathy, names, eye contact.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.06 }, { blocId: "youth", margin: 0.03 }], momentum: 5, narrative: 5 },
        resultText: "You work the room with ease. The likeability gap widens." },
      { id: "policy", text: "Drill into policy specifics.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.05 }, { blocId: "seniors", margin: 0.02 }], momentum: 3, narrative: 2 },
        resultText: "Substance over warmth — the wonks are pleased, the room less so." },
    ] },
  { id: "h08_closing", title: "Closing: Change vs. Experience", subject: "both", oncePerGame: true,
    prompt: "The race resolves to one question — turn the page, or steady the ship? You can only headline one closing argument.",
    trigger: { kind: "scheduled", turn: 7 },
    choices: [
      { id: "d_change", side: "dem", text: "Make it about change and the future.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.06 }, { blocId: "black", margin: 0.05 }, { blocId: "hispanic", margin: 0.04 }, { blocId: "seniors", margin: -0.02 }], momentum: 5, narrative: 4 },
        resultText: "The coalition of the ascendant turns out. Energy is on your side." },
      { id: "d_steady", side: "dem", text: "Reassure the anxious — steady, ready on day one.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.05 }, { blocId: "suburban_women", margin: 0.04 }, { blocId: "youth", margin: -0.02 }], momentum: 4, narrative: 4 },
        resultText: "You calm the nervous middle in a scary moment — at some cost to the spark." },
      { id: "r_experience", side: "rep", text: "Make it about experience and a tested hand.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.06 }, { blocId: "noncollege_white", margin: 0.04 }], momentum: 5, narrative: 4 },
        resultText: "The case for a known quantity reassures older and rural voters." },
      { id: "r_maverick", side: "rep", text: "Run as the maverick reformer — shake up Washington.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "college_white", margin: 0.03 }, { blocId: "noncollege_white", margin: -0.02 }], momentum: 4, narrative: 3 },
        resultText: "The independent streak wins back some suburbanites — and muddles your own message." },
    ] },
];

// ── 2004 · Bush v. Kerry ──────────────────────────────────────────────────
export const HIST_2004: GameEvent[] = [
  { id: "h04_convention", title: "Reporting for Duty", subject: "both", oncePerGame: true,
    prompt: "A wartime election. Kerry opens his convention with a salute — \"reporting for duty\" — running on a decorated Vietnam record and a course correction in Iraq; Bush runs on wartime resolve and a steady hand. Set the frame.",
    trigger: { kind: "scheduled", turn: 0 },
    choices: [
      { id: "d_veteran", side: "dem", text: "Lead with the war record — strength and service.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.05 }, { blocId: "suburban_women", margin: 0.04 }, { blocId: "noncollege_white", margin: 0.02 }], salienceDeltas: { law_and_order: 0.03 }, momentum: 4, narrative: 4 },
        resultText: "The salute lands — though leaning on the military invites a fight on their turf." },
      { id: "d_change", side: "dem", text: "Run as the change candidate — 'we can do better.'",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }, { blocId: "seniors", margin: -0.02 }], salienceDeltas: { economy: 0.05 }, momentum: 4, narrative: 3 },
        resultText: "The reform pitch energizes the base — and cedes the 'safe in wartime' question." },
      { id: "r_resolve", side: "rep", text: "Run on wartime resolve — steady leadership, no flip-flopping.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05, enthusiasm: 0.02 }, { blocId: "seniors", margin: 0.04 }, { blocId: "suburban_women", margin: -0.01 }], salienceDeltas: { law_and_order: 0.05 }, momentum: 5, narrative: 3 },
        resultText: "The strength-and-steadiness frame plays to your incumbency advantage." },
      { id: "r_compassion", side: "rep", text: "Soften the edges — 'compassionate conservatism.'",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "hispanic", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.02 }], momentum: 2, narrative: 3 },
        resultText: "The warmer pitch reaches suburban and Latino voters — and the base wants more fight." },
    ] },
  { id: "h04_swiftboat", title: "The Swift Boat Attacks", subject: "dem", oncePerGame: true,
    prompt: "A group calling itself Swift Boat Veterans for Truth runs ads attacking Kerry's Vietnam record and medals — disputed, but everywhere. The story refuses to die for two weeks.",
    trigger: { kind: "scheduled", turn: 1 },
    choices: [
      { id: "d_fightback", side: "dem", text: "Hit back hard — call the smears what they are.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.04 }, { blocId: "college_white", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.02 }], momentum: 3, narrative: 2 },
        resultText: "You blunt the worst of it — but every day spent defending is a day off your message." },
      { id: "d_ignore", side: "dem", text: "Stay above it — refuse to dignify the smear.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03 }, { blocId: "seniors", margin: -0.04 }, { blocId: "suburban_women", margin: -0.03 }], momentum: -2, narrative: -4 },
        resultText: "The high road lets the attack metastasize. The doubts harden." },
      { id: "r_letitride", side: "rep", text: "Let the outside groups do the work — stay clean.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "seniors", margin: 0.03 }, { blocId: "college_white", margin: -0.01 }], momentum: 4, narrative: 0 },
        resultText: "Plausible deniability holds while the attack does real damage." },
      { id: "r_disavow", side: "rep", text: "Disavow the ads to keep your hands clean.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "college_white", margin: 0.03 }, { blocId: "noncollege_white", margin: -0.03 }], momentum: 1, narrative: 3 },
        resultText: "The high road impresses the suburbs — and the base grumbles you gave up a weapon." },
    ] },
  { id: "h04_debate1", title: "First Debate (Coral Gables)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "Bush and Kerry in Coral Gables — a foreign-policy debate with Iraq front and center. Kerry is crisp and precise; Bush risks looking impatient behind the podium. Command the stage.",
    trigger: { kind: "scheduled", turn: 2 },
    choices: [
      { id: "command", text: "Command the substance — a precise case on the war.", requires: { trait: "debatePrep", min: 70 },
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.05 }, { blocId: "suburban_women", margin: 0.05 }, { blocId: "seniors", margin: 0.03 }], momentum: 6, narrative: 7 },
        resultText: "You look sharp and in command. The instant polls give you the night." },
      { id: "resolve", text: "Project steady resolve — no second-guessing in wartime.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "seniors", margin: 0.04 }, { blocId: "college_white", margin: -0.02 }], momentum: 4, narrative: 2 },
        resultText: "Steadiness reassures the base — but a few exchanges read as stubborn." },
    ] },
  { id: "h04_iraq", title: "The 'Wrong War' Question", subject: "both", oncePerGame: true,
    prompt: "Casualties mount and the rationale for the war frays. The campaign becomes a referendum on whether it was a mistake — and whether you can say so.",
    trigger: { kind: "scheduled", turn: 4 },
    choices: [
      { id: "d_critique", side: "dem", text: "Call it the wrong war at the wrong time.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.03 }, { blocId: "seniors", margin: -0.02 }], salienceDeltas: { law_and_order: 0.04 }, momentum: 3, narrative: 1 },
        resultText: "The base is energized — but 'wavering in wartime' is exactly the attack you feared." },
      { id: "d_competence", side: "dem", text: "Make it about competence — the peace was botched.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "seniors", margin: 0.03 }, { blocId: "college_white", margin: 0.03 }], momentum: 4, narrative: 3 },
        resultText: "Attacking the execution, not the cause, threads the needle with the middle." },
      { id: "r_resolve", side: "rep", text: "Stay the course — resolve over second-guessing.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05, enthusiasm: 0.02 }, { blocId: "seniors", margin: 0.03 }, { blocId: "suburban_women", margin: -0.03 }], salienceDeltas: { law_and_order: 0.04 }, momentum: 4, narrative: 0 },
        resultText: "The unwavering line rallies the base — and the war-weary suburbs wince." },
      { id: "r_flipflop", side: "rep", text: "Paint the opponent as a flip-flopper.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04 }, { blocId: "suburban_women", margin: 0.02 }, { blocId: "college_white", margin: -0.01 }], momentum: 4, narrative: 2 },
        resultText: "The 'for it before he was against it' frame sticks like glue." },
    ] },
  { id: "h04_memo", title: "Rathergate — The Forged Memos", subject: "rep", oncePerGame: true,
    prompt: "CBS's 60 Minutes and Dan Rather air an exposé on Bush's National Guard service — then the documents are exposed as likely forgeries. The story is now about the media, not the record.",
    trigger: { kind: "scheduled", turn: 5 },
    choices: [
      { id: "r_letit", side: "rep", text: "Let it implode — sit back and watch the press squirm.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "seniors", margin: 0.03 }, { blocId: "college_white", margin: -0.01 }], momentum: 4, narrative: 3 },
        resultText: "The media's self-inflicted wound becomes a gift. The base feels vindicated." },
      { id: "r_grievance", side: "rep", text: "Run on media bias — make grievance the message.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.06, enthusiasm: 0.03 }, { blocId: "suburban_women", margin: -0.02 }], momentum: 4, narrative: -1 },
        resultText: "The base is electrified — though dwelling on grievance leaves the suburbs cold." },
      { id: "d_drop", side: "dem", text: "Drop it entirely — pivot back to jobs and Iraq.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04 }, { blocId: "suburban_women", margin: 0.03 }], salienceDeltas: { economy: 0.04 }, momentum: 3, narrative: 3 },
        resultText: "You cut your losses and change the subject to firmer ground." },
      { id: "d_press", side: "dem", text: "Keep pressing the underlying question.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.03 }, { blocId: "college_white", margin: 0.02 }, { blocId: "suburban_women", margin: -0.03 }], momentum: 0, narrative: -3 },
        resultText: "You keep poking — and end up tangled in the discredited story yourself." },
    ] },
  { id: "h04_octobersurprise", title: "The Bin Laden Tape", subject: "both", oncePerGame: true,
    prompt: "Days before the vote, a new Osama bin Laden video airs, dragging the war on terror and national security back to the center of the race.",
    trigger: { kind: "scheduled", turn: 7 },
    choices: [
      { id: "r_strength", side: "rep", text: "Project strength — remind them who keeps you safe.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "seniors", margin: 0.05 }, { blocId: "suburban_women", margin: 0.02 }], salienceDeltas: { law_and_order: 0.06 }, momentum: 5, narrative: 3 },
        resultText: "Security surges back to the top of the ballot — your strongest closing ground." },
      { id: "r_steady", side: "rep", text: "Stay calm and statesmanlike — don't overplay it.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: 0.04 }], momentum: 3, narrative: 4 },
        resultText: "Restraint reads as presidential — and quietly reminds everyone of the stakes." },
      { id: "d_caution", side: "dem", text: "Warn against fear and a forever war.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.05 }, { blocId: "college_white", margin: 0.03 }, { blocId: "seniors", margin: -0.03 }, { blocId: "suburban_women", margin: -0.02 }], momentum: 2, narrative: -2 },
        resultText: "The base nods — but a security scare is the worst week to question toughness." },
      { id: "d_steady", side: "dem", text: "Match the resolve — you'll hunt them down too.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.04 }, { blocId: "suburban_women", margin: 0.03 }, { blocId: "noncollege_white", margin: 0.02 }], salienceDeltas: { law_and_order: 0.03 }, momentum: 3, narrative: 2 },
        resultText: "You refuse to be out-toughed — neutralizing the surprise as best you can." },
    ] },
];

// ── 2000 · Gore v. Bush ───────────────────────────────────────────────────
export const HIST_2000: GameEvent[] = [
  { id: "h00_convention", title: "Stepping Out of Clinton's Shadow", subject: "both", oncePerGame: true,
    prompt: "Peace, prosperity, and a budget surplus — but Al Gore must decide how close to stand to Bill Clinton, popular yet shadowed by impeachment, while George W. Bush runs to \"restore honor and dignity.\" Set your stance.",
    trigger: { kind: "scheduled", turn: 0 },
    choices: [
      { id: "d_ownman", side: "dem", text: "Be your own man — run a populist 'people vs. powerful' pitch.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "youth", margin: 0.03 }, { blocId: "seniors", margin: 0.02 }], salienceDeltas: { economy: 0.04 }, momentum: 4, narrative: 3 },
        resultText: "The fighting-populist framing finds its own voice — and walks away from a good economy." },
      { id: "d_continuity", side: "dem", text: "Run on continuity — don't mess with prosperity.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.05 }, { blocId: "college_white", margin: 0.04 }, { blocId: "youth", margin: -0.02 }], salienceDeltas: { economy: 0.05 }, momentum: 4, narrative: 4 },
        resultText: "The steady-as-she-goes case reassures — but ties you to the baggage too." },
      { id: "r_change", side: "rep", text: "Run as a fresh start — restore honor and dignity.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04 }, { blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: -0.02 }], momentum: 4, narrative: 3 },
        resultText: "The change-of-tone pitch excites voters bored of the incumbents." },
      { id: "r_compassion", side: "rep", text: "Lead with 'compassionate conservatism' and education.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "hispanic", margin: 0.04 }, { blocId: "noncollege_white", margin: -0.02 }], salienceDeltas: { healthcare: 0.03 }, momentum: 3, narrative: 3 },
        resultText: "The softer brand reaches suburban and Latino voters — at some cost to base intensity." },
    ] },
  { id: "h00_debate1", title: "First Debate (Boston)", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "Gore and Bush in Boston. Gore risks the audible sighs and eye-rolls that read as condescending; Bush risks looking out of his depth. Mannerisms will matter as much as substance.",
    trigger: { kind: "scheduled", turn: 2 },
    choices: [
      { id: "command", text: "Command the substance — bury them in policy.", requires: { trait: "policyKnowledge", min: 70 },
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.05 }, { blocId: "seniors", margin: 0.03 }, { blocId: "noncollege_white", margin: -0.03 }], momentum: 4, narrative: 2 },
        resultText: "You win on points — but the sighing and eye-rolling become the story." },
      { id: "likeable", text: "Play it warm and likeable — connect, don't lecture.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.05 }, { blocId: "suburban_women", margin: 0.04 }], momentum: 5, narrative: 5 },
        resultText: "Affable beats encyclopedic. The 'who'd you rather have a beer with' crowd warms to you." },
    ] },
  { id: "h00_vpdebate", title: "A Cordial VP Debate", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "An unusually civil, substantive undercard. No fireworks — just two running mates making the case. Whose ticket does it help?",
    trigger: { kind: "scheduled", turn: 3 },
    choices: [
      { id: "gravitas", text: "Sell experience and a steady hand.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.04 }, { blocId: "college_white", margin: 0.03 }], momentum: 3, narrative: 3 },
        resultText: "The grown-up tone reassures voters worried about the top of the ticket." },
      { id: "future", text: "Sell freshness and the next generation.",
        effects: { blocDeltas: [{ blocId: "youth", margin: 0.04 }, { blocId: "suburban_women", margin: 0.03 }], momentum: 3, narrative: 2 },
        resultText: "A forward-looking pitch nudges younger and suburban voters your way." },
    ] },
  { id: "h00_townhall", title: "The Town-Hall Debate", subject: "both", isDebate: true, oncePerGame: true,
    prompt: "Gore and Bush in a town-hall format with undecided voters in the room. Body language is everything — when Gore strides over and looms at Bush's shoulder, one awkward move can define you.",
    trigger: { kind: "scheduled", turn: 5 },
    choices: [
      { id: "connect", text: "Work the room — empathy and eye contact.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.05 }, { blocId: "black", margin: 0.03 }], momentum: 4, narrative: 4 },
        resultText: "You connect with the room. The reaction shots all break your way." },
      { id: "loom", text: "Assert dominance — crowd the stage and your opponent.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03 }, { blocId: "suburban_women", margin: -0.05 }], momentum: 1, narrative: -4 },
        resultText: "The move reads as aggressive and odd. The clip loops for days." },
    ] },
  { id: "h00_ads", title: "The 'RATS' Ad", subject: "rep", oncePerGame: true,
    prompt: "A Bush attack ad is caught flashing the word \"RATS\" for a single frame as \"BUREAUCRATS\" scrolls past — a thirtieth of a second of alleged subliminal messaging. It's silly, and it's leading every newscast.",
    trigger: { kind: "scheduled", turn: 6 },
    choices: [
      { id: "r_laugh", side: "rep", text: "Laugh it off and pull the ad.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.03 }, { blocId: "suburban_women", margin: 0.02 }], momentum: 1, narrative: 2 },
        resultText: "A light touch makes the story evaporate by the weekend." },
      { id: "r_deny", side: "rep", text: "Deny everything and keep the ad running.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.02 }, { blocId: "college_white", margin: -0.03 }], momentum: 0, narrative: -3 },
        resultText: "The denial keeps the silly story alive for an extra week of bad coverage." },
      { id: "d_pounce", side: "dem", text: "Pounce — call it a dirty trick.",
        effects: { blocDeltas: [{ blocId: "college_white", margin: 0.03 }, { blocId: "youth", margin: 0.02 }, { blocId: "noncollege_white", margin: -0.02 }], momentum: 1, narrative: -1 },
        resultText: "You score a small point — but risk looking like you're sweating the small stuff." },
      { id: "d_ignore", side: "dem", text: "Stay focused on prescription drugs and Social Security.",
        effects: { blocDeltas: [{ blocId: "seniors", margin: 0.04 }, { blocId: "suburban_women", margin: 0.02 }], salienceDeltas: { healthcare: 0.04 }, momentum: 2, narrative: 2 },
        resultText: "Discipline on the issues seniors care about beats chasing a gimmick." },
    ] },
  { id: "h00_dui", title: "Bush's DUI Surfaces", subject: "rep", oncePerGame: true,
    prompt: "Days before the vote, a 1976 drunk-driving arrest of George W. Bush surfaces and dominates the final weekend. It's decades-old news, but the timing is brutal.",
    trigger: { kind: "scheduled", turn: 7 },
    choices: [
      { id: "r_honest", side: "rep", text: "Get ahead of it — own it, be honest, move on.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: 0.03 }], momentum: 3, narrative: 4 },
        resultText: "Candor blunts the hit. Voters respect the straight answer in the final hours." },
      { id: "r_deflect", side: "rep", text: "Cry dirty trick and blame the timing.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.03, enthusiasm: 0.02 }, { blocId: "suburban_women", margin: -0.03 }], momentum: 2, narrative: -2 },
        resultText: "The base rallies to your defense — but the deflection keeps the story alive." },
      { id: "d_exploit", side: "dem", text: "Exploit it — quietly question their character to the last.",
        effects: { blocDeltas: [{ blocId: "noncollege_white", margin: 0.04 }, { blocId: "seniors", margin: 0.03 }, { blocId: "youth", margin: -0.02 }], momentum: 3, narrative: -1 },
        resultText: "The character hit lands with some — but late mud splashes back on you, too." },
      { id: "d_positive", side: "dem", text: "Resist the temptation — close on your own positive message.",
        effects: { blocDeltas: [{ blocId: "suburban_women", margin: 0.04 }, { blocId: "seniors", margin: 0.03 }], momentum: 3, narrative: 3 },
        resultText: "Staying positive in the final hours keeps the high ground — and lets it speak for itself." },
    ] },
];
