// Portrait URLs keyed by full candidate / running-mate name. Anyone without an
// entry falls back to an initials avatar (see ui/Avatar). Local files in
// public/images: official / Wikimedia Commons portraits (public domain / CC),
// fetched and resized to 400px. Regenerate with scripts, do not hand-edit paths.
export const PORTRAITS: Record<string, string> = {
  "Al Gore": "images/algore.jpg",
  "Amy Klobuchar": "images/amyklobuchar.jpg",
  "Andy Beshear": "images/andybeshear.jpg",
  "Barack Obama": "images/barackobama.jpg",
  "Chris Christie": "images/chrischristie.jpg",
  "Colin Powell": "images/colinpowell.jpg",
  "Cory Booker": "images/corybooker.jpg",
  "Dick Cheney": "images/dickcheney.jpg",
  "Donald Trump": "images/trump.jpg",
  "Doug Burgum": "images/dougburgum.jpg",
  "Elizabeth Warren": "images/elizabethwarren.jpg",
  "Evan Bayh": "images/evanbayh.jpg",
  "George W. Bush": "images/georgewbush.jpg",
  "Gretchen Whitmer": "images/gretchenwhitmer.jpg",
  "Hillary Clinton": "images/hillaryclinton.jpg",
  "JD Vance": "images/jdvance.jpg",
  "Jeff Sessions": "images/jeffsessions.jpg",
  "Joe Biden": "images/biden.jpg",
  "Joe Lieberman": "images/joelieberman.jpg",
  "John Edwards": "images/johnedwards.jpg",
  "John Kerry": "images/johnkerry.jpg",
  "John McCain": "images/johnmccain.jpg",
  "Josh Shapiro": "images/joshshapiro.jpg",
  "Kamala Harris": "images/harris.jpg",
  "Kristi Noem": "images/kristinoem.jpg",
  "Marco Rubio": "images/marcorubio.jpg",
  "Mark Kelly": "images/markkelly.jpg",
  "Mark Warner": "images/markwarner.jpg",
  "Mike Pence": "images/pence.jpg",
  "Mitt Romney": "images/mittromney.jpg",
  "Newt Gingrich": "images/newtgingrich.jpg",
  "Nikki Haley": "images/nikkihaley.jpg",
  "Paul Ryan": "images/paulryan.jpg",
  "Rob Portman": "images/robportman.jpg",
  "Sarah Palin": "images/sarahpalin.jpg",
  "Tim Kaine": "images/timkaine.jpg",
  "Tim Pawlenty": "images/timpawlenty.jpg",
  "Tim Scott": "images/timscott.jpg",
  "Tim Walz": "images/timwalz.jpg",
  "Tom Cotton": "images/tomcotton.jpg",
  "Tom Ridge": "images/tomridge.jpg",
  "Val Demings": "images/valdemings.jpg",
};

export function portraitFor(name: string): string | undefined {
  return PORTRAITS[name];
}
